import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Eye, Search, X } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { Modal } from './Modal';

export function AuditLog(){
 const[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[q,setQ]=useState(''),[actor,setActor]=useState(''),[entity,setEntity]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[count,setCount]=useState(0),[actors,setActors]=useState<any[]>([]);
 async function load(){let query=supabase!.from('audit_logs').select('id,actor,action,entity_type,entity_id,metadata,created_at,profiles(full_name)',{count:'exact'}).order('created_at',{ascending:false});const clean=q.trim().replace(/[%_,]/g,'');if(clean)query=query.or('action.ilike.%'+clean+'%,entity_type.ilike.%'+clean+'%,entity_id.ilike.%'+clean+'%');if(actor)query=query.eq('actor',actor);if(entity)query=query.eq('entity_type',entity);if(from)query=query.gte('created_at',from+'T00:00:00');if(to)query=query.lte('created_at',to+'T23:59:59');const{data,error,count}=await query.range((page-1)*pageSize,page*pageSize-1);if(!error){setRows(data||[]);setCount(count||0)}}
 useEffect(()=>{void load()},[q,actor,entity,from,to,page,pageSize]);
 useEffect(()=>{supabase!.from('profiles').select('id,full_name').order('full_name').then(({data})=>setActors(data||[]))},[]);
 const entities=[...new Set(rows.map(r=>r.entity_type))].sort();
 return <section className="admin-page audit-page"><div className="page-title"><div><p className="eyebrow">ACCOUNTABILITY, BUILT IN</p><h1>Audit Log</h1></div></div>
 <div className="audit-filters"><div className="category-search"><Search size={17}/><input className="control" placeholder="Search action, entity or ID…" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/>{q&&<button className="search-clear" onClick={()=>setQ('')}><X size={15}/></button>}</div><select value={actor} onChange={e=>{setActor(e.target.value);setPage(1)}}><option value="">All actors</option>{actors.map(a=><option key={a.id} value={a.id}>{a.full_name||a.id}</option>)}</select><input type="text" placeholder="Entity type" list="audit-entities" value={entity} onChange={e=>{setEntity(e.target.value);setPage(1)}}/><datalist id="audit-entities">{entities.map(e=><option key={e} value={e}/>)}</datalist><label>From<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><label>To<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label></div>
 <p className="muted small audit-count">{count} events · newest first</p>
 <div className="table-wrap"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>Entity ID</th><th className="actions-cell">Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td>{r.profiles?.full_name||'System'}</td><td><span className={'audit-action '+r.action}>{r.action}</span></td><td>{r.entity_type}</td><td className="audit-id">{r.entity_id||'—'}</td><td className="actions-cell"><button className="icon-button" data-tooltip="View details" onClick={()=>setSelected(r)}><Eye size={18}/></button></td></tr>)}{!rows.length&&<tr><td colSpan={6}>No audit events found.</td></tr>}</tbody><tfoot><tr><td colSpan={6}><div className="category-pagination"><div className="table-size"><span>Rows per page</span><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option><option>100</option></select></div><span className="pagination-range">{count?Math.min((page-1)*pageSize+1,count):0}–{Math.min(page*pageSize,count)} of {count}</span><div className="pagination-controls"><button className="pagination-button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>Page {page} of {Math.max(1,Math.ceil(count/pageSize))}</span><button className="pagination-button" disabled={page>=Math.ceil(count/pageSize)} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div></td></tr></tfoot></table></div>
 {selected&&<Modal title="Audit event details" onClose={()=>setSelected(null)}><div className="audit-detail"><div className="audit-detail-grid"><div><span>Time</span><strong>{new Date(selected.created_at).toLocaleString()}</strong></div><div><span>Actor</span><strong>{selected.profiles?.full_name||'System'}</strong></div><div><span>Action</span><strong>{selected.action}</strong></div><div><span>Entity</span><strong>{selected.entity_type}</strong></div><div className="full"><span>Entity ID</span><strong>{selected.entity_id||'—'}</strong></div></div><div className="audit-metadata"><span>Metadata</span><pre>{JSON.stringify(selected.metadata,null,2)}</pre></div><div className="product-form-actions"><button className="secondary-button" onClick={()=>setSelected(null)}>Close</button></div></div></Modal>}</section>
}