import {guardSubmit} from './submitGuard';
import { FormEvent, useEffect, useState } from 'react';
import { ErrorPopup } from './ErrorPopup';
import { ChevronLeft, ChevronRight, Eye, Pencil, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { Modal } from './Modal';

export function Categories({permissions}:{permissions:string[]}){
 const[rows,setRows]=useState<any[]>([]),[viewing,setViewing]=useState<any|null>(null),[edit,setEdit]=useState<any|null|undefined>(undefined),[deleting,setDeleting]=useState<any|null>(null);
 const[error,setError]=useState(''),[q,setQ]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[count,setCount]=useState(0),[pageSize,setPageSize]=useState(25),[activeFilter,setActiveFilter]=useState<'all'|'active'|'inactive'>('all'); const canEdit=permissions.includes('products.edit');
 async function load(){let query=supabase!.from('categories').select('id,title,active,created_at',{count:'exact'}).order('created_at',{ascending:false});if(search)query=query.ilike('title','%'+search.replace(/[%_]/g,'')+'%');if(activeFilter!=='all')query=query.eq('active',activeFilter==='active');const{data,count}=await query.range((page-1)*pageSize,page*pageSize-1);setRows(data||[]);setCount(count||0)}
 useEffect(()=>{void load()},[search,page,pageSize,activeFilter]);
 useEffect(()=>{setPage(1);setSearch(q.trim())},[q]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget);const title=String(fd.get('title')||'').trim(),active=fd.get('active')==='on';if(!title){setError('Name is required.');return}const slug=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'category-'+crypto.randomUUID();const q=edit?.id?supabase!.from('categories').update({title,active}).eq('id',edit.id):supabase!.from('categories').insert({title,active,slug});const{error}=await q;if(error){setError(error.message);return}setEdit(undefined);void load()}
 async function toggle(r:any){if(!canEdit)return;setError('');const{error}=await supabase!.from('categories').update({active:!r.active}).eq('id',r.id);if(error){setError(error.message);return}void load()}
 async function remove(){if(!deleting)return;setError('');const{error}=await supabase!.from('categories').delete().eq('id',deleting.id);if(error){setError(error.code==='23503'?'This category is in use.':'Unable to delete category.');return}setDeleting(null);void load()}
 return <section className="admin-page"><div className="page-title"><div><p className="eyebrow">WORKSPACE</p><h1>Categories</h1></div>{canEdit&&<button className="primary-button add-record-button" onClick={()=>setEdit(null)}><span className="add-record-icon"><Plus size={16}/></span><span>Add category</span></button>}</div>
 <div className="category-toolbar"><div className="category-search"><Search size={17}/><input className="control" aria-label="Search Categories" placeholder="Search categories…" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button className="search-clear" aria-label="Clear search" onClick={()=>setQ('')}><X size={15}/></button>}</div><div className="table-filters"><label className="filter-select"><span>Status</span><select className="control" value={activeFilter} onChange={e=>{setActiveFilter(e.target.value as 'all'|'active'|'inactive');setPage(1)}}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div></div>
 <div className="table-wrap"><table><thead><tr><th>Name</th><th>Active</th><th className="actions-cell"><span className="actions-heading">Actions <button className="table-refresh-icon" data-tooltip="Refresh" aria-label="Refresh table" onClick={()=>void load()}><RefreshCw size={15}/></button></span></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.title}</td><td><button className={'status-toggle '+(r.active?'on':'')} disabled={!canEdit} aria-label={r.active?'Deactivate category':'Activate category'} onClick={()=>toggle(r)}><span/></button></td><td className="actions-cell"><div className="table-actions"><button className="icon-button" data-tooltip="View" aria-label={'View '+r.title} onClick={()=>setViewing(r)}><Eye size={18}/></button>{canEdit&&<><button className="icon-button" data-tooltip="Edit" onClick={()=>setEdit(r)}><Pencil size={18}/></button><button className="icon-button error" data-tooltip="Delete" onClick={()=>{setError('');setDeleting(r)}}><Trash2 size={18}/></button></>}</div></td></tr>)}</tbody><tfoot><tr><td colSpan={3}><div className="category-pagination"><div className="table-size"><span>Rows per page</span><select aria-label="Rows per page" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option value={10}>10</option><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></div><span className="pagination-range">{count?Math.min((page-1)*pageSize+1,count):0}–{Math.min(page*pageSize,count)} of {count}</span><div className="pagination-controls"><button className="pagination-button" aria-label="Previous page" disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}><ChevronLeft size={17}/></button><span>Page {page} of {Math.max(1,Math.ceil(count/pageSize))}</span><button className="pagination-button" aria-label="Next page" disabled={page>=Math.ceil(count/pageSize)} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div></td></tr></tfoot></table></div>

 {viewing&&<Modal title="Category details" onClose={()=>setViewing(null)}><div className="category-view"><div className="category-view-head"><div><span className="section-kicker">CATEGORY</span><h3>{viewing.title}</h3></div><span className={'category-view-status '+(viewing.active?'active':'')}>{viewing.active?'Active':'Inactive'}</span></div><div className="category-view-details"><div><span>Name</span><strong>{viewing.title}</strong></div><div><span>Status</span><strong>{viewing.active?'Active':'Inactive'}</strong></div><div><span>Created</span><strong>{viewing.created_at?new Date(viewing.created_at).toLocaleDateString():'—'}</strong></div></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setViewing(null)}>Close</button>{canEdit&&<button className="primary-button" onClick={()=>{const r=viewing;setViewing(null);setEdit(r)}}><Pencil size={15}/> Edit category</button>}</div></div></Modal>}

 {edit!==undefined&&<Modal title={edit?'Edit category':'Add category'} onClose={()=>setEdit(undefined)}><form className="editor-form category-editor category-editor-modern" onSubmit={guardSubmit(save)}><label className="category-name">Category name<span className="field-help">Shown throughout the store and CRM.</span><input name="title" required autoFocus defaultValue={edit?.title||''} placeholder="e.g. Desk reminders"/></label><label className="category-active"><span>Visibility</span><span className="field-help">Make this category available on the website.</span><span className="toggle-row"><span>{edit?.active??true?'Active':'Active'}</span><span className="form-toggle"><input type="checkbox" name="active" defaultChecked={edit?.active??true}/><span className="toggle-track"><span/></span></span></span></label><div className="modal-actions full"><button type="button" className="secondary-button" onClick={()=>setEdit(undefined)}>Cancel</button><button className="primary-button">{edit?'Save changes':'Create category'}</button></div></form></Modal>}
 {deleting&&<Modal title="Delete category?" onClose={()=>setDeleting(null)}><div className="confirm-body modern-confirm"><div className="danger-icon"><Trash2 size={21}/></div><div><h3>Remove “{deleting.title}”?</h3><p>This category can only be deleted when no products are assigned to it.</p></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setDeleting(null)}>Cancel</button><button className="danger-button" onClick={remove}>Delete category</button></div></div></Modal>}{error&&<ErrorPopup message={error} onClose={()=>setError('')}/>} </section>
}
