import { FormEvent, useEffect, useState } from 'react';
import { Eye, Pencil, Plus, Trash2 } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { Modal } from './Modal';

export function Categories({permissions}:{permissions:string[]}){
 const[rows,setRows]=useState<any[]>([]),[edit,setEdit]=useState<any|null|undefined>(undefined),[view,setView]=useState<any|null>(null),[deleting,setDeleting]=useState<any|null>(null);
 const[error,setError]=useState(''),[q,setQ]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[count,setCount]=useState(0); const canEdit=permissions.includes('products.edit'); const pageSize=25;
 async function load(){let query=supabase!.from('categories').select('id,title,active,created_at',{count:'exact'}).order('created_at',{ascending:false});if(search)query=query.ilike('title','%'+search.replace(/[%_]/g,'')+'%');const{data,count}=await query.range((page-1)*pageSize,page*pageSize-1);setRows(data||[]);setCount(count||0)}
 useEffect(()=>{void load()},[search,page]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget);const title=String(fd.get('title')||'').trim(),active=fd.get('active')==='on';if(!title){setError('Name is required.');return}const slug=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'category-'+crypto.randomUUID();const q=edit?.id?supabase!.from('categories').update({title,active}).eq('id',edit.id):supabase!.from('categories').insert({title,active,slug});const{error}=await q;if(error){setError(error.message);return}setEdit(undefined);void load()}
 async function toggle(r:any){if(!canEdit)return;await supabase!.from('categories').update({active:!r.active}).eq('id',r.id);void load()}
 async function remove(){if(!deleting)return;setError('');const{error}=await supabase!.from('categories').delete().eq('id',deleting.id);if(error){setError(error.code==='23503'?'This category is in use.':'Unable to delete category.');return}setDeleting(null);void load()}
 return <section className="admin-page"><div className="page-title"><div><p className="eyebrow">WORKSPACE</p><h1>Categories</h1></div>{canEdit&&<button className="primary-button" onClick={()=>setEdit(null)}><Plus size={17}/> Add category</button>}</div>
 <form className="category-search row" onSubmit={e=>{e.preventDefault();setPage(1);setSearch(q.trim())}}><input className="control" aria-label="Search Categories" placeholder="Search categories…" value={q} onChange={e=>{const value=e.target.value;setQ(value);if(!value.trim()){setPage(1);setSearch('')}}}/><button className="secondary-button">Search</button></form>
 <div className="table-wrap"><table><thead><tr><th>Name</th><th>Active</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.title}</td><td><button className={'status-toggle '+(r.active?'on':'')} disabled={!canEdit} aria-label={r.active?'Deactivate category':'Activate category'} onClick={()=>toggle(r)}><span/></button></td><td className="actions-cell"><div className="table-actions"><button className="icon-button" title="View" onClick={()=>setView(r)}><Eye size={18}/></button>{canEdit&&<><button className="icon-button" title="Edit" onClick={()=>setEdit(r)}><Pencil size={18}/></button><button className="icon-button error" title="Delete" onClick={()=>{setError('');setDeleting(r)}}><Trash2 size={18}/></button></>}</div></td></tr>)}</tbody><tfoot><tr><td colSpan={3}><div className="category-pagination"><div className="pagination-actions">{page>1&&<button className="text-button" onClick={()=>setPage(p=>p-1)}>← Previous</button>}</div><span className="small muted">{count} records · Page {page}</span><div className="pagination-actions">{count>page*pageSize&&<button className="text-button" onClick={()=>setPage(p=>p+1)}>Next →</button>}</div></div></td></tr></tfoot></table></div>
 {view&&<Modal title="Category" onClose={()=>setView(null)}><div className="editor-form category-editor category-view"><label className="category-name">Name<input value={view.title} disabled/></label><label className="category-active">Active<span className={'status-toggle '+(view.active?'on':'')} aria-label={view.active?'Active':'Inactive'}><span/></span></label></div></Modal>}
 {edit!==undefined&&<Modal title={edit?'Edit category':'Add category'} onClose={()=>setEdit(undefined)}><form className="editor-form category-editor" onSubmit={save}><label className="category-name">Name<input name="title" required defaultValue={edit?.title||''}/></label><label className="category-active">Active<span className="form-toggle"><input type="checkbox" name="active" defaultChecked={edit?.active??true}/><span className="toggle-track"><span/></span></span></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button">Save</button></form></Modal>}
 {deleting&&<Modal title="Delete category?" onClose={()=>setDeleting(null)}><div className="confirm-body"><p>Delete {deleting.title}? Products will remain, without this category.</p>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="secondary-button" onClick={()=>setDeleting(null)}>Cancel</button><button className="danger-button" onClick={remove}>Delete category</button></div></div></Modal>}</section>
}
