import { BrandLoader } from '../BrandLoader';
import{useEffect,useState}from'react';import{CheckCircle2,ChevronLeft,ChevronRight,ExternalLink,Eye,FileText,Image as ImageIcon,Pencil,Plus,RefreshCw,Search,Trash2,Upload,X}from'lucide-react';import{supabase}from'../lib/supabase';import{Modal}from'./Modal';import{ErrorPopup}from'./ErrorPopup';

function date(v:any){const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(d)}
function label(a:any,i=0){return a?.title||a?.url||('Design file '+(i+1))}
export function DesignsAdmin({permissions}:{permissions:string[]}){
 const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(25),[count,setCount]=useState(0),[selected,setSelected]=useState<string|null>(null),[editing,setEditing]=useState<string|null>(null),[creating,setCreating]=useState(false),[deleting,setDeleting]=useState<any|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('');
 async function load(){if(!supabase)return;setLoading(true);const from=(page-1)*size,term=q.trim().replace(/[%_,()]/g,'');let query=supabase.from('designs').select('id,name,code,created_at,design_assets(id,title,path,url,asset_type)',{count:'exact'}).order('created_at',{ascending:false});if(term){const{data:matches}=await supabase.from('design_assets').select('design_id').or('title.ilike.%'+term+'%,url.ilike.%'+term+'%,path.ilike.%'+term+'%').limit(1000);const ids=[...new Set((matches||[]).map(a=>a.design_id))];query=query.or('name.ilike.%'+term+'%,code.ilike.%'+term+'%'+(ids.length?',id.in.('+ids.join(',')+')':''))}const{data,error,count}=await query.range(from,from+size-1);setLoading(false);if(error){setError(error.message);return}setRows(data||[]);setCount(count||0);setError('')}

 useEffect(()=>{void load()},[q,page,size]);
 async function remove(){if(!supabase||!deleting)return;setError('');const paths=(deleting.design_assets||[]).filter((a:any)=>a.path).map((a:any)=>a.path);const{data,error}=await supabase.from('designs').delete().eq('id',deleting.id).select('id');if(error){setError(error.code==='23503'?'This design is in use and cannot be deleted.':error.message);return}if(!data?.length){setError('Could not delete this design. Please refresh and try again.');return}setDeleting(null);if(paths.length)await supabase.storage.from('production-files').remove(paths);setSuccess('Design deleted successfully.');await load()}

 const canEdit=permissions.includes('designs.edit'),pages=Math.max(1,Math.ceil(count/size));
 return <section className="admin-page crm-list-page"><div className="page-title"><div><p className="eyebrow">DESIGN FILES</p><h1>Design Library</h1><p className="muted">Store design images, PDF files and related links.</p></div>{canEdit&&<button className="primary-button add-record-button" onClick={()=>setCreating(true)}><Plus size={16}/> Add design</button>}</div><div className="category-toolbar"><div className="category-search"><Search size={17}/><input className="control" aria-label="Search designs" placeholder="Search name, code or asset URL…" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/>{q&&<button className="search-clear" aria-label="Clear search" onClick={()=>{setQ('');setPage(1)}}><X size={15}/></button>}</div></div><div className="table-wrap"><table><thead><tr><th>Design</th><th>Code</th><th>Created</th><th className="actions-cell"><span className="actions-heading">Actions <button className="table-refresh-icon" data-tooltip="Refresh" aria-label="Refresh table" onClick={()=>void load()}><RefreshCw size={15}/></button></span></th></tr></thead><tbody>{loading&&<tr className="table-empty-row"><td colSpan={4}><div className="table-empty-state"><BrandLoader label="Loading designs" compact/></div></td></tr>}{!loading&&!rows.length&&<tr className="table-empty-row"><td colSpan={4}><div className="table-empty-state"><strong>{q?'No designs found':'No designs yet'}</strong><span>{q?'Try another search.':'Upload images or PDFs, or add a related URL.'}</span></div></td></tr>}{!loading&&rows.map((r:any,idx:number)=>{const a=r.design_assets||[];return <tr key={r.id}><td><strong>{r.name}</strong><span className="design-list-asset">{a.length} {a.length===1?'asset':'assets'}</span></td><td><code>{r.code}</code></td><td>{date(r.created_at)}</td><td className="actions-cell"><div className="table-actions"><button className="icon-button" data-tooltip="View" onClick={()=>setSelected(r.id)}><Eye size={18}/></button>{canEdit&&<><button className="icon-button" data-tooltip="Edit" onClick={()=>setEditing(r.id)}><Pencil size={18}/></button><button className="icon-button error" data-tooltip="Delete" onClick={()=>setDeleting(r)}><Trash2 size={18}/></button></>}</div></td></tr>})}</tbody><tfoot><tr><td colSpan={4}><div className="category-pagination"><div className="table-size"><span>Rows per page</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option><option>100</option></select></div><span>{count?Math.min((page-1)*size+1,count):0}–{Math.min(page*size,count)} of {count}</span><div className="pagination-controls"><button className="pagination-button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>Page {page} of {pages}</span><button className="pagination-button" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div></td></tr></tfoot></table></div>
 {(selected||editing||creating)&&<DesignAssetsEditor id={selected||editing} mode={creating?'add':editing?'edit':'view'} canEdit={canEdit} onEdit={selected&&canEdit?()=>{setEditing(selected);setSelected(null)}:undefined} onClose={()=>{setSelected(null);setEditing(null);setCreating(false);void load()}} onSaved={async()=>{setSelected(null);setEditing(null);setCreating(false);setSuccess('Design saved successfully.');await load()}} onSuccess={message=>setSuccess(message)}/>}
 {success&&<Modal title={success.includes('deleted')?'Deleted successfully':'Saved successfully'} compact onClose={()=>setSuccess('')}><div className="modern-confirm design-success-confirm" role="status"><span className="design-success-icon"><CheckCircle2 size={21}/></span><div><h3>{success}</h3><p>Your changes are now available in the Design Library.</p></div><div className="modal-actions"><button className="primary-button" onClick={()=>setSuccess('')}>OK</button></div></div></Modal>}
 {deleting&&<Modal title="Delete design?" onClose={()=>setDeleting(null)}><div className="confirm-body modern-confirm"><div className="danger-icon"><Trash2 size={21}/></div><div><h3>Remove this design?</h3><p>Its uploaded design files and related links will be removed. Designs already used by products or orders cannot be deleted.</p></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setDeleting(null)}>Cancel</button><button className="danger-button" onClick={()=>void remove()}>Delete design</button></div></div></Modal>}<ErrorPopup message={error} onClose={()=>setError('')}/></section>
}

function DesignAssetsEditor({id,mode,canEdit,onEdit,onClose,onSaved,onSuccess}:{id:string|null;mode:'view'|'edit'|'add';canEdit:boolean;onEdit?:()=>void;onClose:()=>void;onSaved:()=>void;onSuccess:(message:string)=>void}){
 const[designName,setDesignName]=useState(''),[designCode,setDesignCode]=useState(''),[createdId,setCreatedId]=useState<string|null>(null),[assets,setAssets]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[signed,setSigned]=useState<Record<string,string>>({}),[addType,setAddType]=useState<'pdf'|'image'|'url'|null>(null),[name,setName]=useState(''),[file,setFile]=useState<File|null>(null),[url,setUrl]=useState('');const editable=canEdit&&mode!=='view',designId=createdId||id;
 async function load(currentId=designId){if(!supabase||!currentId)return;const[{data:design},{data,error}]=await Promise.all([supabase.from('designs').select('name,code').eq('id',currentId).single(),supabase.from('design_assets').select('*').eq('design_id',currentId).order('created_at')]);if(design){setDesignName(design.name);setDesignCode(design.code)}if(error){setError(error.message);return}setAssets(data||[]);const map:Record<string,string>={};for(const a of data||[]){if(a.path){const{data:s}=await supabase.storage.from('production-files').createSignedUrl(a.path,3600);if(s?.signedUrl)map[a.id]=s.signedUrl}}setSigned(map)}
 useEffect(()=>{void load()},[id]);
 async function saveDetails(){if(!supabase||!designName.trim()||!designCode.trim())return;setBusy(true);setError('');const values={name:designName.trim(),code:designCode.trim()};const result=designId?await supabase.from('designs').update(values).eq('id',designId):await supabase.from('designs').insert(values).select('id').single();setBusy(false);if(result.error){setError(result.error.code==='23505'?'This design code is already in use.':result.error.message);return}if(!designId){setCreatedId(result.data!.id);onSuccess('Design created successfully.')}else onSaved()}

 function resetAdd(){setAddType(null);setName('');setFile(null);setUrl('')}
 async function addAsset(){if(!supabase||!addType)return;if(!name.trim()){setError('Name is required.');return}if(addType==='url'){try{new URL(url)}catch{setError('Please enter a complete URL including https://');return}}else if(!file){setError('Choose a file to upload.');return}setBusy(true);setError('');if(!designId){setBusy(false);setError('Save the design name and code first.');return}
 let record:any={design_id:designId,title:name.trim(),asset_type:addType,path:null,url:null};
 if(addType==='url')record.url=url.trim();else{const ok=addType==='image'?file!.type.startsWith('image/'):(file!.type==='application/pdf'||file!.name.toLowerCase().endsWith('.pdf'));if(!ok){setBusy(false);setError(addType==='image'?'Please choose an image file.':'Please choose a PDF file.');return}const safe=file!.name.replace(/[^a-zA-Z0-9._-]+/g,'-'),path='designs/'+designId+'/'+crypto.randomUUID()+'-'+safe;const{error}=await supabase.storage.from('production-files').upload(path,file!,{contentType:file!.type,upsert:false});if(error){setBusy(false);setError(error.message);return}record.path=path}
 const{error}=await supabase.from('design_assets').insert(record);setBusy(false);if(error){setError(error.message);return}resetAdd();await load(designId);onSuccess('Design asset saved successfully.')}
 async function removeAsset(a:any){if(!supabase)return;const{data,error}=await supabase.from('design_assets').delete().eq('id',a.id).select('id');if(error||!data?.length){setError(error?.message||'Could not remove this asset.');return}if(a.path)await supabase.storage.from('production-files').remove([a.path]);await load();onSuccess('Design asset deleted successfully.')}

 function open(a:any){const u=a.asset_type==='url'?a.url:signed[a.id];if(u)window.open(u,'_blank','noopener,noreferrer')}
 const groups=[{type:'pdf' as const,title:'PDF files',description:'Print files and production references.',empty:'No PDF files added yet.'},{type:'image' as const,title:'Images',description:'Artwork and visual references.',empty:'No images added yet.'},{type:'url' as const,title:'Related links',description:'External files and helpful resources.',empty:'No links added yet.'}];
 return <Modal title={mode==='add'?'Add design':mode==='edit'?'Edit design':'Design details'} onClose={onClose}><div className={'design-editor design-editor-modern design-assets-only '+(mode==='view'?'design-detail':'')}>
  <section className="design-existing design-identity"><div className="design-step-heading"><span className="design-step-number">01</span><div><h3>Design details</h3><p>Name and code used throughout the CRM.</p></div></div><div className="design-step-content design-identity-fields"><label>Name<input value={designName} onChange={e=>setDesignName(e.target.value)} disabled={!editable||Boolean(createdId)} placeholder="Design name" required/></label><label>Code<input value={designCode} onChange={e=>setDesignCode(e.target.value)} disabled={!editable||Boolean(createdId)} placeholder="e.g. DES-001" required/></label></div></section>
  {mode==='add'&&!designId&&<p className="design-editor-intro">Save the name and code, then add PDFs, images or related links.</p>}
  {groups.map((g,index)=>{const list=assets.filter((a:any)=>a.asset_type===g.type);return <section className="design-existing" key={g.type}><div className="design-step-heading"><span className="design-step-number">{String(index+2).padStart(2,'0')}</span><div><h3>{g.title}</h3><p>{g.description}</p></div></div><div className="design-step-content"><div className="design-section-heading"><span>{list.length} {list.length===1?'item':'items'}</span>{editable&&designId&&<button className="primary-button" onClick={()=>{resetAdd();setAddType(g.type)}}><Plus size={15}/> Add {g.type==='url'?'URL':g.type==='pdf'?'PDF':'image'}</button>}</div><div className="table-wrap"><table><thead><tr><th>Name</th><th>{g.type==='url'?'URL':'File'}</th>{editable&&<th className="actions-cell">Actions</th>}</tr></thead><tbody>{!list.length&&<tr className="table-empty-row"><td colSpan={editable?3:2}><div className="table-empty-state"><strong>{g.empty}</strong></div></td></tr>}{list.map((a:any)=><tr key={a.id}><td><strong>{label(a)}</strong></td><td>{g.type==='url'?<button className="link-button" onClick={()=>open(a)}>{a.url}</button>:<button className="secondary-button" onClick={()=>open(a)}>Open {g.type==='pdf'?'PDF':'image'}</button>}</td>{editable&&<td className="actions-cell"><button className="icon-button error" data-tooltip="Delete" onClick={()=>void removeAsset(a)}><Trash2 size={17}/></button></td>}</tr>)}</tbody></table></div></div></section>})}
 </div>
 <div className="design-modal-footer">{mode==='view'?<><button className="secondary-button" onClick={onClose}>Close</button>{canEdit&&onEdit&&<button className="primary-button" onClick={onEdit}><Pencil size={15}/> Edit design</button>}</>:<><button className="secondary-button" onClick={onClose}>{mode==='add'&&!designId?'Cancel':'Done'}</button>{editable&&!createdId&&<button className="primary-button" disabled={busy||!designName.trim()||!designCode.trim()} onClick={()=>void saveDetails()}>{busy?'Saving…':designId?'Save changes':'Create design'}</button>}</>}</div>
 {addType&&<Modal title={'Add '+(addType==='url'?'related URL':addType==='pdf'?'PDF':'image')} onClose={resetAdd}><div className="form-grid"><label><span>Name</span><input className="control" value={name} onChange={e=>setName(e.target.value)} placeholder={addType==='url'?'Reference name':'File name'}/></label>{addType==='url'?<label><span>URL</span><input className="control" type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com"/></label>:<label><span>File</span><input className="control" type="file" accept={addType==='pdf'?'application/pdf,.pdf':'image/*'} onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}</div><div className="modal-actions"><button className="secondary-button" onClick={resetAdd}>Cancel</button><button className="primary-button" disabled={busy||!name.trim()||(addType==='url'?!url.trim():!file)} onClick={()=>void addAsset()}>{busy?'Adding…':'Add'}</button></div></Modal>}
 <ErrorPopup message={error} onClose={()=>setError('')}/>
 </Modal>
}
