import{useEffect,useState}from'react';import{ChevronLeft,ChevronRight,ExternalLink,Eye,FileText,Image as ImageIcon,Pencil,Plus,RefreshCw,Trash2,Upload}from'lucide-react';import{supabase}from'../lib/supabase';import{Modal}from'./Modal';

function date(v:any){const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(d)}
function label(a:any,i=0){return a?.title||a?.url||('Design file '+(i+1))}
export function DesignsAdmin({permissions}:{permissions:string[]}){
 const[rows,setRows]=useState<any[]>([]),[page,setPage]=useState(1),[size,setSize]=useState(25),[count,setCount]=useState(0),[selected,setSelected]=useState<string|null>(null),[editing,setEditing]=useState<string|null>(null),[creating,setCreating]=useState(false),[deleting,setDeleting]=useState<any|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){if(!supabase)return;setLoading(true);const from=(page-1)*size,{data,error,count}=await supabase.from('designs').select('id,created_at,design_assets(id,title,path,url,asset_type)',{count:'exact'}).order('created_at',{ascending:false}).range(from,from+size-1);setLoading(false);if(error){setError(error.message);return}setRows(data||[]);setCount(count||0);setError('')}
 useEffect(()=>{void load()},[page,size]);
 async function remove(){if(!supabase||!deleting)return;setError('');const assets=deleting.design_assets||[];const paths=assets.filter((a:any)=>a.path).map((a:any)=>a.path);if(paths.length)await supabase.storage.from('production-files').remove(paths);const{error}=await supabase.from('designs').delete().eq('id',deleting.id);if(error){setError(error.code==='23503'?'This design is in use and cannot be deleted.':error.message);return}setDeleting(null);await load()}
 const canEdit=permissions.includes('designs.edit'),pages=Math.max(1,Math.ceil(count/size));
 return <section className="admin-page"><div className="page-title"><div><p className="eyebrow">DESIGN FILES</p><h1>Design Library</h1><p className="muted">Store design images, PDF files and related links.</p></div>{canEdit&&<button className="primary-button add-record-button" onClick={()=>setCreating(true)}><Plus size={16}/> Add design</button>}</div>{error&&<div className="notice">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Design</th><th>Images</th><th>PDFs</th><th>Links</th><th>Created</th><th className="actions-cell"><span className="actions-heading">Actions <button className="table-refresh-icon" data-tooltip="Refresh" aria-label="Refresh table" onClick={()=>void load()}><RefreshCw size={15}/></button></span></th></tr></thead><tbody>{!loading&&!rows.length&&<tr className="table-empty-row"><td colSpan={6}><div className="table-empty-state"><strong>No designs yet</strong><span>Upload images or PDFs, or add a related URL.</span></div></td></tr>}{rows.map((r:any,idx:number)=>{const a=r.design_assets||[];return <tr key={r.id}><td><strong>{label(a[0],(page-1)*size+idx)}</strong></td><td>{a.filter((x:any)=>x.asset_type==='image').length}</td><td>{a.filter((x:any)=>x.asset_type==='pdf').length}</td><td>{a.filter((x:any)=>x.asset_type==='url').length}</td><td>{date(r.created_at)}</td><td className="actions-cell"><div className="table-actions"><button className="icon-button" data-tooltip="View" onClick={()=>setSelected(r.id)}><Eye size={18}/></button>{canEdit&&<><button className="icon-button" data-tooltip="Edit" onClick={()=>setEditing(r.id)}><Pencil size={18}/></button><button className="icon-button error" data-tooltip="Delete" onClick={()=>setDeleting(r)}><Trash2 size={18}/></button></>}</div></td></tr>})}</tbody><tfoot><tr><td colSpan={6}><div className="category-pagination"><div className="table-size"><span>Rows per page</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option><option>100</option></select></div><span>{count?Math.min((page-1)*size+1,count):0}–{Math.min(page*size,count)} of {count}</span><div className="pagination-controls"><button className="pagination-button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>Page {page} of {pages}</span><button className="pagination-button" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div></td></tr></tfoot></table></div>
 {(selected||editing||creating)&&<DesignAssetsEditor id={selected||editing} mode={creating?'add':editing?'edit':'view'} canEdit={canEdit} onEdit={selected&&canEdit?()=>{setEditing(selected);setSelected(null)}:undefined} onClose={()=>{setSelected(null);setEditing(null);setCreating(false)}} onSaved={async()=>{setSelected(null);setEditing(null);setCreating(false);await load()}}/>}
 {deleting&&<Modal title="Delete design?" onClose={()=>setDeleting(null)}><div className="confirm-body modern-confirm"><div className="danger-icon"><Trash2 size={21}/></div><div><h3>Remove this design?</h3><p>Its uploaded design files and related links will be removed. Designs already used by products or orders cannot be deleted.</p></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setDeleting(null)}>Cancel</button><button className="danger-button" onClick={()=>void remove()}>Delete design</button></div></div></Modal>}</section>
}

function DesignAssetsEditor({id,mode,canEdit,onEdit,onClose,onSaved}:{id:string|null;mode:'view'|'edit'|'add';canEdit:boolean;onEdit?:()=>void;onClose:()=>void;onSaved:()=>void}){
 const[assets,setAssets]=useState<any[]>([]),[files,setFiles]=useState<File[]>([]),[urls,setUrls]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[signed,setSigned]=useState<Record<string,string>>({});const editable=canEdit&&mode!=='view';
 async function load(){if(!supabase||!id)return;const{data,error}=await supabase.from('design_assets').select('*').eq('design_id',id).order('created_at');if(error){setError(error.message);return}setAssets(data||[]);const map:Record<string,string>={};for(const a of data||[]){if(a.path){const{data:s}=await supabase.storage.from('production-files').createSignedUrl(a.path,3600);if(s?.signedUrl)map[a.id]=s.signedUrl}}setSigned(map)}
 useEffect(()=>{void load()},[id]);
 async function save(){if(!supabase)return;const linkList=urls.split(/\n/).map(x=>x.trim()).filter(Boolean);if(!id&&!files.length&&!linkList.length){setError('Upload at least one image/PDF or add a related URL.');return}setBusy(true);setError('');let designId=id;let created=false;if(!designId){const{data,error}=await supabase.from('designs').insert({}).select('id').single();if(error||!data){setBusy(false);setError(error?.message||'Could not create design.');return}designId=data.id;created=true}
 const records:any[]=[];for(const file of files){const isImage=file.type.startsWith('image/'),isPdf=file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf');if(!isImage&&!isPdf){setError('Only images and PDF files are allowed.');setBusy(false);return}const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path='designs/'+designId+'/'+crypto.randomUUID()+'-'+safe;const{error}=await supabase.storage.from('production-files').upload(path,file,{contentType:file.type,upsert:false});if(error){setBusy(false);setError(error.message);return}records.push({design_id:designId,path,title:file.name,asset_type:isImage?'image':'pdf',url:null})}
 for(const url of linkList){try{new URL(url)}catch{setBusy(false);setError('Please enter complete URLs including https://');return}records.push({design_id:designId,path:null,title:null,asset_type:'url',url})}
 if(records.length){const{error}=await supabase.from('design_assets').insert(records);if(error){setBusy(false);setError(error.message);return}}
 setBusy(false);if(created||records.length)onSaved();else onClose()}
 async function removeAsset(a:any){if(!supabase)return;if(a.path){const{error}=await supabase.storage.from('production-files').remove([a.path]);if(error){setError(error.message);return}}const{error}=await supabase.from('design_assets').delete().eq('id',a.id);if(error){setError(error.message);return}await load()}
 function open(a:any){const u=a.asset_type==='url'?a.url:signed[a.id];if(u)window.open(u,'_blank','noopener,noreferrer')}
 return <Modal title={mode==='add'?'Add design':mode==='edit'?'Edit design':'Design details'} onClose={onClose}>{error&&<div className="notice">{error}</div>}<div className={'design-editor design-editor-modern design-assets-only '+(mode==='view'?'design-detail':'')}>
  {editable&&<div className="design-upload-grid"><label className="design-dropzone"><Upload size={24}/><strong>Upload images or PDFs</strong><span>Select multiple files at once</span><input type="file" multiple accept="image/*,application/pdf,.pdf" onChange={e=>setFiles(Array.from(e.target.files||[]))}/>{files.length>0&&<small>{files.length} file{files.length===1?'':'s'} selected</small>}</label><label className="design-url-field"><strong>Related URLs</strong><span>Add one URL per line.</span><textarea className="control" rows={7} placeholder={"https://example.com/design\nhttps://example.com/reference"} value={urls} onChange={e=>setUrls(e.target.value)}/></label></div>}
  {id&&<section className="design-existing"><h3>Design files & links</h3><div className="design-asset-grid">{assets.map((a:any)=><div className="design-asset-card" key={a.id}>{a.asset_type==='image'&&signed[a.id]?<img src={signed[a.id]} alt={a.title||'Design'}/>:a.asset_type==='pdf'?<FileText size={30}/>:<ExternalLink size={30}/>}<div><strong>{label(a)}</strong><small>{a.asset_type==='url'?'Related URL':a.asset_type.toUpperCase()}</small></div><button className="secondary-button" onClick={()=>open(a)}>Open</button>{editable&&<button className="icon-button error" data-tooltip="Remove" onClick={()=>void removeAsset(a)}><Trash2 size={17}/></button>}</div>)}</div>{!assets.length&&<p className="muted">No files or links attached yet.</p>}</section>}
  <div className="modal-actions">{mode==='view'?<><button className="secondary-button" onClick={onClose}>Close</button>{canEdit&&onEdit&&<button className="primary-button" onClick={onEdit}><Pencil size={15}/> Edit design</button>}</>:<><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy||(!id&&!files.length&&!urls.trim())} onClick={()=>void save()}>{busy?'Saving…':mode==='add'?'Add design':'Save additions'}</button></>}</div>
 </div></Modal>
}
