import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Eye, Mail, Search, Users, X } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { Modal } from './Modal';

type Message={id:string;full_name:string;email:string;message:string;created_at:string};
type Subscriber={id:string;email:string;consent_at:string};
function when(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}

export function InboxAdmin(){
 const[tab,setTab]=useState<'messages'|'subscribers'>('messages'),[rows,setRows]=useState<(Message|Subscriber)[]>([]),[selected,setSelected]=useState<Message|null>(null),[q,setQ]=useState(''),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[count,setCount]=useState(0),[messageCount,setMessageCount]=useState(0),[subscriberCount,setSubscriberCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){if(!supabase)return;setLoading(true);setError('');const from=(page-1)*pageSize,to=page*pageSize-1;let query:any;if(tab==='messages'){query=supabase.from('contact_messages').select('id,full_name,email,message,created_at',{count:'exact'}).order('created_at',{ascending:false});if(q.trim()){const safe=q.trim().replace(/[%_,]/g,'');query=query.or('full_name.ilike.%'+safe+'%,email.ilike.%'+safe+'%,message.ilike.%'+safe+'%')}}else{query=supabase.from('newsletter_subscribers').select('id,email,consent_at',{count:'exact'}).order('consent_at',{ascending:false});if(q.trim())query=query.ilike('email','%'+q.trim().replace(/[%_]/g,'')+'%')}const{data,count,error}=await query.range(from,to);if(error)setError(error.message);else{setRows(data||[]);setCount(count||0)}setLoading(false)}
 useEffect(()=>{void load()},[tab,q,page,pageSize]);
 useEffect(()=>{if(!supabase)return;(async()=>{const[m,s]=await Promise.all([supabase.from('contact_messages').select('id',{count:'exact',head:true}),supabase.from('newsletter_subscribers').select('id',{count:'exact',head:true})]);setMessageCount(m.count||0);setSubscriberCount(s.count||0)})()},[]);
 const pages=Math.max(1,Math.ceil(count/pageSize));
 return <section className="admin-page"><div className="page-title"><div><p className="eyebrow">CUSTOMER CARE</p><h1>Messages</h1><p className="muted">Contact messages and newsletter subscribers from the storefront.</p></div></div>
 <div className="inbox-stats"><div><Mail size={18}/><span>Messages</span><strong>{messageCount}</strong></div><div><Users size={18}/><span>Subscribers</span><strong>{subscriberCount}</strong></div></div>
 <div className="category-toolbar"><div className="category-search"><Search size={17}/><input className="control" aria-label="Search inbox" placeholder={tab==='messages'?'Search messages…':'Search subscribers…'} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/>{q&&<button className="search-clear" aria-label="Clear search" onClick={()=>{setQ('');setPage(1)}}><X size={15}/></button>}</div><div className="table-filters"><span className="filter-label">View</span><button className={'filter-chip '+(tab==='messages'?'active':'')} onClick={()=>{setTab('messages');setQ('');setPage(1)}}>Messages {messageCount}</button><button className={'filter-chip '+(tab==='subscribers'?'active':'')} onClick={()=>{setTab('subscribers');setQ('');setPage(1)}}>Newsletter {subscriberCount}</button></div></div>
 {error?<div className="notice">{error}</div>:<div className="table-wrap"><table><thead>{tab==='messages'?<tr><th>From</th><th>Email</th><th>Message</th><th>Received</th><th>Actions</th></tr>:<tr><th>Email</th><th>Consent recorded</th><th>Actions</th></tr>}</thead><tbody>{!loading&&!rows.length&&<tr className="table-empty-row"><td colSpan={tab==='messages'?5:3}><div className="table-empty-state"><Mail size={20}/><strong>{q?'No results found':'No messages yet'}</strong><span>{q?'Try a different search.':tab==='messages'?'New contact messages will appear here.':'Newsletter subscribers will appear here.'}</span></div></td></tr>}{!loading&&rows.map((r:any)=>tab==='messages'?<tr key={r.id}><td>{r.full_name}</td><td>{r.email}</td><td><span className="inbox-preview">{r.message}</span></td><td>{when(r.created_at)}</td><td className="actions-cell"><div className="table-actions"><button className="icon-button" data-tooltip="View" aria-label={'View message from '+r.full_name} onClick={()=>setSelected(r)}><Eye size={18}/></button></div></td></tr>:<tr key={r.id}><td>{r.email}</td><td>{when(r.consent_at)}</td><td className="actions-cell"></td></tr>)}</tbody><tfoot><tr><td colSpan={tab==='messages'?5:3}><div className="category-pagination"><div className="table-size"><span>Rows per page</span><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option><option>100</option></select></div><span className="pagination-range">{count?Math.min((page-1)*pageSize+1,count):0}–{Math.min(page*pageSize,count)} of {count}</span><div className="pagination-controls"><button className="pagination-button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>Page {page} of {pages}</span><button className="pagination-button" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div></td></tr></tfoot></table>{loading&&<div className="admin-empty">Loading…</div>}</div>}
 {selected&&<Modal title="Customer message" onClose={()=>setSelected(null)}><div className="message-detail"><div className="message-sender"><div className="message-avatar">{selected.full_name.trim().charAt(0).toUpperCase()}</div><div><strong>{selected.full_name}</strong><a href={'mailto:'+selected.email}>{selected.email}</a><span>{when(selected.created_at)}</span></div></div><div className="message-body">{selected.message}</div><div className="modal-actions"><button className="secondary-button" onClick={()=>setSelected(null)}>Close</button><a className="primary-button" href={'mailto:'+selected.email}>Reply by email</a></div></div></Modal>}</section>
}