import { useEffect, useMemo, useState } from 'react';
import { Mail, Search, Users, X } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { Modal } from './Modal';

type Message={id:string;full_name:string;email:string;message:string;created_at:string};
type Subscriber={id:string;email:string;consent_at:string};

function when(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}

export function InboxAdmin(){
 const[messages,setMessages]=useState<Message[]>([]),[subscribers,setSubscribers]=useState<Subscriber[]>([]),[tab,setTab]=useState<'messages'|'subscribers'>('messages'),[selected,setSelected]=useState<Message|null>(null),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let live=true;(async()=>{if(!supabase)return;setLoading(true);const[m,s]=await Promise.all([supabase.from('contact_messages').select('id,full_name,email,message,created_at').order('created_at',{ascending:false}).limit(100),supabase.from('newsletter_subscribers').select('id,email,consent_at').order('consent_at',{ascending:false}).limit(100)]);if(!live)return;if(m.error||s.error)setError('Inbox unavailable.');else{setMessages((m.data||[]) as Message[]);setSubscribers((s.data||[]) as Subscriber[])}setLoading(false)})();return()=>{live=false}},[]);
 const fm=useMemo(()=>{const x=q.trim().toLowerCase();return !x?messages:messages.filter(m=>(m.full_name+' '+m.email+' '+m.message).toLowerCase().includes(x))},[messages,q]);
 const fs=useMemo(()=>{const x=q.trim().toLowerCase();return !x?subscribers:subscribers.filter(s=>s.email.toLowerCase().includes(x))},[subscribers,q]);
 return <section className="admin-page inbox-admin"><div className="admin-page-head"><div><p className="eyebrow">CUSTOMER CARE</p><h1>Messages</h1><p className="muted">Contact messages and newsletter subscribers from the storefront.</p></div></div><div className="inbox-stats"><div><Mail size={18}/><span>Messages</span><strong>{messages.length}</strong></div><div><Users size={18}/><span>Subscribers</span><strong>{subscribers.length}</strong></div></div><div className="inbox-toolbar"><div className="inbox-tabs"><button className={tab==='messages'?'active':''} onClick={()=>{setTab('messages');setQ('')}}>Messages <span>{messages.length}</span></button><button className={tab==='subscribers'?'active':''} onClick={()=>{setTab('subscribers');setQ('')}}>Newsletter <span>{subscribers.length}</span></button></div><label className="inbox-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tab==='messages'?'Search messages…':'Search subscribers…'}/>{q&&<button aria-label="Clear search" onClick={()=>setQ('')}><X size={14}/></button>}</label></div>{error?<div className="notice">{error}</div>:loading?<div className="admin-empty">Loading inbox…</div>:tab==='messages'?<div className="inbox-table-wrap"><table className="inbox-table"><thead><tr><th>From</th><th>Message</th><th>Received</th><th></th></tr></thead><tbody>{fm.map(m=><tr key={m.id} onClick={()=>setSelected(m)}><td><strong>{m.full_name}</strong><span>{m.email}</span></td><td><span className="inbox-preview">{m.message}</span></td><td><span>{when(m.created_at)}</span></td><td><button className="secondary-button inbox-open" onClick={e=>{e.stopPropagation();setSelected(m)}}>Open</button></td></tr>)}</tbody></table>{!fm.length&&<div className="admin-empty">No messages found.</div>}</div>:<div className="inbox-table-wrap"><table className="inbox-table subscriber-table"><thead><tr><th>Email</th><th>Consent recorded</th></tr></thead><tbody>{fs.map(s=><tr key={s.id}><td><strong>{s.email}</strong></td><td>{when(s.consent_at)}</td></tr>)}</tbody></table>{!fs.length&&<div className="admin-empty">No subscribers found.</div>}</div>}{selected&&<Modal title="Customer message" onClose={()=>setSelected(null)}><div className="message-detail"><div className="message-sender"><div className="message-avatar">{selected.full_name.trim().charAt(0).toUpperCase()}</div><div><strong>{selected.full_name}</strong><a href={'mailto:'+selected.email}>{selected.email}</a><span>{when(selected.created_at)}</span></div></div><div className="message-body">{selected.message}</div><div className="modal-actions"><button className="secondary-button" onClick={()=>setSelected(null)}>Close</button><a className="primary-button" href={'mailto:'+selected.email}>Reply by email</a></div></div></Modal>}</section>
}
