import { FormEvent, useEffect, useState } from 'react';
import { Eye, Pencil, Plus, Trash2 } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { Modal } from './Modal';

export function InventoryAdmin({permissions}:{permissions:string[]}){
 const[rows,setRows]=useState<any[]>([]),[edit,setEdit]=useState<any|null|undefined>(undefined),[view,setView]=useState<any|null>(null),[movements,setMovements]=useState<any[]>([]),[deleting,setDeleting]=useState<any|null>(null);const[error,setError]=useState('');const canEdit=permissions.includes('inventory.edit');
 async function load(){const[{data},{data:m}]=await Promise.all([supabase!.from('inventory_items').select('id,sku,title,quantity,low_stock_threshold').order('title'),supabase!.from('inventory_movements').select('id,inventory_item_id,delta,reason,movement_type,order_number,product_title,variant_sku,allocation_delta,created_at').order('created_at',{ascending:false}).limit(100)]);setRows(data||[]);setMovements(m||[])}
 async function remove(){if(!deleting)return;setError('');const{error}=await supabase!.from('inventory_items').delete().eq('id',deleting.id);if(error){setError(error.code==='23503'?'This inventory item has variant or movement history and cannot be deleted.':error.message);return}setDeleting(null);void load()}
 useEffect(()=>{void load()},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget);const data={sku:String(fd.get('sku')||'').trim(),title:String(fd.get('title')||'').trim(),quantity:Number(fd.get('quantity')||0),low_stock_threshold:Number(fd.get('low_stock_threshold')||0)};if(!data.sku||!data.title){setError('SKU and title are required.');return}if(edit?.id){const delta=data.quantity-edit.quantity;const{error:u}=await supabase!.from('inventory_items').update({sku:data.sku,title:data.title,low_stock_threshold:data.low_stock_threshold}).eq('id',edit.id);if(u){setError(u.message);return}if(delta){const{error:a}=await supabase!.rpc('adjust_inventory',{p_id:edit.id,p_delta:delta,p_reason:'Inventory quantity edited'});if(a){setError(a.message);return}}}else{const{error}=await supabase!.from('inventory_items').insert(data);if(error){setError(error.message);return}}setEdit(undefined);void load()}
 return <section className="admin-page"><div className="page-title"><div><p className="eyebrow">WORKSPACE</p><h1>Inventory</h1></div>{canEdit&&<button className="primary-button" onClick={()=>setEdit(null)}><Plus size={17}/> Add inventory</button>}</div><div className="table-wrap"><table><thead><tr><th>Item</th><th>SKU</th><th>Physical</th><th>Low stock at</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.sku}</td><td>{r.quantity}</td><td>{r.low_stock_threshold}</td><td>{r.quantity<=r.low_stock_threshold?'Low stock':'Available'}</td><td className="actions-cell"><div className="table-actions"><button className="icon-button" title="View" onClick={()=>setView(r)}><Eye size={18}/></button>{canEdit&&<><button className="icon-button" title="Edit" onClick={()=>setEdit(r)}><Pencil size={18}/></button><button className="icon-button error" title="Delete" onClick={()=>{setError('');setDeleting(r)}}><Trash2 size={18}/></button></>}</div></td></tr>)}</tbody></table></div>
 <div className="inventory-history"><h2>Recent inventory movements</h2><div className="table-wrap"><table><thead><tr><th>Time</th><th>Type</th><th>Item</th><th>Change</th><th>Product / variant</th><th>Reason</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString()}</td><td>{m.movement_type||'Adjustment'}</td><td>{rows.find(r=>r.id===m.inventory_item_id)?.title||'—'}</td><td>{m.delta||m.allocation_delta||0}</td><td>{[m.product_title,m.variant_sku].filter(Boolean).join(' · ')||'—'}</td><td>{m.order_number?'Order '+m.order_number:m.reason||'—'}</td></tr>)}{!movements.length&&<tr><td colSpan={6}>No movements yet.</td></tr>)}</tbody></table></div></div>
 {view&&<Modal title="Inventory item" onClose={()=>setView(null)}><div className="editor-form two-col"><label>Title<input value={view.title} disabled/></label><label>SKU<input value={view.sku} disabled/></label><label>Physical quantity<input value={view.quantity} disabled/></label><label>Low stock threshold<input value={view.low_stock_threshold} disabled/></label></div></Modal>}
 {edit!==undefined&&<Modal title={edit?'Edit inventory':'Add inventory'} onClose={()=>setEdit(undefined)}><form className="editor-form" onSubmit={save}><label>Title<input name="title" required defaultValue={edit?.title||''}/></label><label>SKU<input name="sku" required defaultValue={edit?.sku||''}/></label><label>Physical quantity<input name="quantity" type="number" min="0" required defaultValue={edit?.quantity??0}/></label><label>Low stock threshold<input name="low_stock_threshold" type="number" min="0" required defaultValue={edit?.low_stock_threshold??0}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button">Save</button></form></Modal>}{deleting&&<Modal title="Delete inventory item?" onClose={()=>setDeleting(null)}><div className="confirm-body"><p>Delete {deleting.title}?</p>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="secondary-button" onClick={()=>setDeleting(null)}>Cancel</button><button className="danger-button" onClick={remove}>Delete inventory item</button></div></div></Modal>}</section>
}
