import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { Modal } from './Modal';

export function InventoryAdmin({permissions}:{permissions:string[]}){
 const[rows,setRows]=useState<any[]>([]),[edit,setEdit]=useState<any|null|undefined>(undefined);const[error,setError]=useState('');const canEdit=permissions.includes('inventory.edit');
 async function load(){const{data}=await supabase!.from('inventory_items').select('id,sku,title,quantity,low_stock_threshold').order('title');setRows(data||[])}
 useEffect(()=>{void load()},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget);const data={sku:String(fd.get('sku')||'').trim(),title:String(fd.get('title')||'').trim(),quantity:Number(fd.get('quantity')||0),low_stock_threshold:Number(fd.get('low_stock_threshold')||0)};if(!data.sku||!data.title){setError('SKU and title are required.');return}if(edit?.id){const delta=data.quantity-edit.quantity;const{error:u}=await supabase!.from('inventory_items').update({sku:data.sku,title:data.title,low_stock_threshold:data.low_stock_threshold}).eq('id',edit.id);if(u){setError(u.message);return}if(delta){const{error:a}=await supabase!.rpc('adjust_inventory',{p_id:edit.id,p_delta:delta,p_reason:'Inventory quantity edited'});if(a){setError(a.message);return}}}else{const{error}=await supabase!.from('inventory_items').insert(data);if(error){setError(error.message);return}}setEdit(undefined);void load()}
 return <section className="admin-page"><div className="page-title"><div><p className="eyebrow">WORKSPACE</p><h1>Inventory</h1></div>{canEdit&&<button className="primary-button" onClick={()=>setEdit(null)}>Add inventory</button>}</div><div className="table-wrap"><table><thead><tr><th>Item</th><th>SKU</th><th>Physical</th><th>Low stock at</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.sku}</td><td>{r.quantity}</td><td>{r.low_stock_threshold}</td><td>{r.quantity<=r.low_stock_threshold?'Low stock':'Available'}</td><td>{canEdit&&<button className="link-button" onClick={()=>setEdit(r)}>Edit</button>}</td></tr>)}</tbody></table></div>
 {edit!==undefined&&<Modal title={edit?'Edit inventory':'Add inventory'} onClose={()=>setEdit(undefined)}><form className="editor-form" onSubmit={save}><label>Title<input name="title" required defaultValue={edit?.title||''}/></label><label>SKU<input name="sku" required defaultValue={edit?.sku||''}/></label><label>Physical quantity<input name="quantity" type="number" min="0" required defaultValue={edit?.quantity??0}/></label><label>Low stock threshold<input name="low_stock_threshold" type="number" min="0" required defaultValue={edit?.low_stock_threshold??0}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button">Save</button></form></Modal>}</section>
}
