import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { Modal } from './Modal';

export function ProductDetails({product,onClose,permissions}:{product:any;onClose:()=>void;permissions:string[]}){
 const[variants,setVariants]=useState<any[]>([]),[images,setImages]=useState<any[]>([]),[inventory,setInventory]=useState<any[]>([]),[editVariant,setEditVariant]=useState<any|null|undefined>(undefined),[error,setError]=useState('');
 const canEdit=permissions.includes('products.edit'),canMedia=permissions.includes('media.edit');
 async function load(){const[{data:v},{data:i},{data:inv}]=await Promise.all([supabase!.from('product_variants').select('*').eq('product_id',product.id).order('created_at'),supabase!.from('product_images').select('*').eq('product_id',product.id).order('position'),supabase!.from('inventory_items').select('id,sku,title,quantity').order('title')]);setVariants(v||[]);setImages(i||[]);setInventory(inv||[])}
 useEffect(()=>{void load()},[product.id]);
 async function saveVariant(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget);const data={product_id:product.id,sku:String(fd.get('sku')||'').trim(),color:String(fd.get('color')||'').trim(),price_override:fd.get('price')?Math.round(Number(fd.get('price'))*100):null,image_url:String(fd.get('image_url')||'')||null,active:fd.get('active')==='on',inventory_item_id:fd.get('inventory_item_id')||null,stock_allocation:Number(fd.get('stock_allocation')||0)};const{error}=await supabase!.rpc('save_variant',{p_id:editVariant?.id||null,p_data:data});if(error){setError(error.message);return}setEditVariant(undefined);void load()}
 async function deleteVariant(){if(!editVariant?.id)return;const{error}=await supabase!.from('product_variants').delete().eq('id',editVariant.id);if(error){setError(error.code==='23503'?'This variant has order or stock history. Turn it inactive instead.':error.message);return}setEditVariant(undefined);void load()}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget),file=fd.get('file') as File;if(!file?.size){setError('Choose an image.');return}const ext=file.name.split('.').pop()||'jpg',path=product.id+'/'+crypto.randomUUID()+'.'+ext;const{error:u}=await supabase!.storage.from('product-images').upload(path,file);if(u){setError(u.message);return}const{data:url}=supabase!.storage.from('product-images').getPublicUrl(path);const{error:i}=await supabase!.from('product_images').insert({product_id:product.id,url:url.publicUrl,alt:String(fd.get('alt')||product.title),position:Number(fd.get('position')||images.length)});if(i){setError(i.message);return}(e.currentTarget as HTMLFormElement).reset();void load()}
 async function deleteImage(row:any){const{error}=await supabase!.from('product_images').delete().eq('id',row.id);if(error)setError(error.message);else void load()}
 return <Modal title={product.title} onClose={onClose}><div className="detail-stack"><section><div className="section-head"><h3>Variants & stock allocation</h3>{canEdit&&<button className="primary-button small" onClick={()=>setEditVariant(null)}>Add variant</button>}</div><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Color</th><th>Inventory</th><th>Allocation</th><th>Active</th><th>Actions</th></tr></thead><tbody>{variants.map(v=><tr key={v.id}><td>{v.sku}</td><td>{v.color||'—'}</td><td>{inventory.find(i=>i.id===v.inventory_item_id)?.title||'—'}</td><td>{v.stock_allocation}</td><td>{v.active?'Yes':'No'}</td><td><button className="link-button" onClick={()=>setEditVariant(v)}>{canEdit?'Edit':'View'}</button></td></tr>)}{!variants.length&&<tr><td colSpan={6}>No variants yet.</td></tr>}</tbody></table></div></section>
 <section><div className="section-head"><h3>Product images</h3></div><div className="image-admin-grid">{images.map(i=><div className="image-admin-card" key={i.id}><img src={i.url} alt={i.alt||product.title}/><span>{i.alt||'Product image'} · #{i.position}</span>{canMedia&&<button className="link-button danger" onClick={()=>deleteImage(i)}>Delete</button>}</div>)}</div>{canMedia&&<form className="editor-form image-upload" onSubmit={upload}><label>Image<input name="file" type="file" accept="image/*" required/></label><label>Alt text<input name="alt" defaultValue={product.title}/></label><label>Position<input name="position" type="number" min="0" defaultValue={images.length}/></label><button className="primary-button">Upload image</button></form>}</section>{error&&<p className="form-error">{error}</p>}</div>
 {editVariant!==undefined&&<Modal title={editVariant?'Edit variant':'Add variant'} onClose={()=>setEditVariant(undefined)}><form className="editor-form two-col" onSubmit={saveVariant}><label>SKU<input name="sku" required defaultValue={editVariant?.sku||''} disabled={!canEdit}/></label><label>Color<input name="color" defaultValue={editVariant?.color||''} disabled={!canEdit}/></label><label>Price override (USD)<input name="price" type="number" min="0" step=".01" defaultValue={editVariant?.price_override!=null?editVariant.price_override/100:''} disabled={!canEdit}/></label><label>Inventory item<select name="inventory_item_id" defaultValue={editVariant?.inventory_item_id||''} disabled={!canEdit}><option value="">None</option>{inventory.map(i=><option key={i.id} value={i.id}>{i.title} ({i.quantity} physical)</option>)}</select></label><label>Stock allocation<input name="stock_allocation" type="number" min="0" defaultValue={editVariant?.stock_allocation||0} disabled={!canEdit}/></label><label>Image URL<input name="image_url" defaultValue={editVariant?.image_url||''} disabled={!canEdit}/></label><label className="check"><input name="active" type="checkbox" defaultChecked={editVariant?.active??true} disabled={!canEdit}/> Active</label>{error&&<p className="form-error full">{error}</p>}<div className="modal-actions full">{editVariant?.id&&canEdit&&<button type="button" className="danger-button" onClick={deleteVariant}>Delete variant</button>}{canEdit&&<button className="primary-button">Save variant</button>}</div></form></Modal>}</Modal>
}
