import {guardSubmit} from './submitGuard';
import { FormEvent, useEffect, useState } from 'react';
import { ErrorPopup } from './ErrorPopup';
import { supabase } from '../lib/supabase';
import { Modal } from './Modal';
import { ProductDetails } from './ProductDetails';
import { ChevronLeft, ChevronRight, Eye, Pencil, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react';

export function ProductsAdmin({permissions}:{permissions:string[]}){
 const[rows,setRows]=useState<any[]>([]),[cats,setCats]=useState<any[]>([]),[designs,setDesigns]=useState<any[]>([]),[inventory,setInventory]=useState<any[]>([]),[adding,setAdding]=useState(false),[details,setDetails]=useState<{product:any;mode:'view'|'edit'}|null>(null),[deleting,setDeleting]=useState<any|null>(null),[error,setError]=useState(''),[q,setQ]=useState(''),[statusFilter,setStatusFilter]=useState<'all'|'active'|'draft'>('all'),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[count,setCount]=useState(0);
 const canEdit=permissions.includes('products.edit');
 async function load(){let query=supabase!.from('products').select('*',{count:'exact'}).order('created_at',{ascending:false});if(q.trim())query=query.or('title.ilike.%'+q.trim().replace(/[%_,]/g,'')+'%,sku.ilike.%'+q.trim().replace(/[%_,]/g,'')+'%');if(statusFilter!=='all')query=query.eq('status',statusFilter==='active'?'Active':'Draft');const[{data:r,count},{data:c},{data:d},{data:inv}]=await Promise.all([query.range((page-1)*pageSize,page*pageSize-1),supabase!.from('categories').select('id,title').order('title'),supabase!.from('designs').select('id,title').order('title'),supabase!.from('inventory_items').select('id,sku,title,quantity').order('title')]);setRows(r||[]);setCount(count||0);setCats(c||[]);setDesigns(d||[]);setInventory(inv||[])}
 useEffect(()=>{void load()},[q,statusFilter,page,pageSize]);
 async function saveNew(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget),title=String(fd.get('title')||'').trim(),sku=String(fd.get('sku')||'').trim();if(!title||!sku){setError('Title and SKU are required.');return}const data:any={title,sku,description:String(fd.get('description')||''),price:Number(Number(fd.get('price')||0).toFixed(2)),category_id:fd.get('category_id')||null,design_id:fd.get('design_id')||null,status:fd.get('status')==='on'?'Active':'Draft',featured:fd.get('featured')==='on',bestseller:fd.get('bestseller')==='on',new_arrival:fd.get('new_arrival')==='on',seo_title:fd.get('seo_title')||null,seo_description:fd.get('seo_description')||null,slug:title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'product-'+crypto.randomUUID()};const{data:created,error}=await supabase!.from('products').insert(data).select('id').single();if(error||!created){setError(error?.message||'Unable to create product.');return}const inventoryId=fd.get('inventory_item_id')||null,allocation=Number(fd.get('stock_allocation')||0);if(inventoryId||allocation){const{error:stockError}=await supabase!.rpc('save_product_inventory',{p_product_id:created.id,p_inventory_item_id:inventoryId,p_stock_allocation:allocation});if(stockError){await supabase!.from('products').delete().eq('id',created.id);setError(stockError.message);return}}setAdding(false);void load()}
 async function remove(){if(!deleting)return;const{error}=await supabase!.rpc('delete_product',{p_id:deleting.id});if(error){setError(error.message);return}setDeleting(null);void load()}
 return <section className="admin-page">
  <div className="page-title"><div><p className="eyebrow">WORKSPACE</p><h1>Products</h1></div>{canEdit&&<button className="primary-button add-record-button" onClick={()=>{setError('');setAdding(true)}}><span className="add-record-icon"><Plus size={16}/></span><span>Add product</span></button>}</div>
  <div className="category-toolbar"><div className="category-search"><Search size={17}/><input className="control" aria-label="Search products" placeholder="Search products or SKU…" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/>{q&&<button className="search-clear" aria-label="Clear search" onClick={()=>{setQ('');setPage(1)}}><X size={15}/></button>}</div><div className="table-filters"><label className="filter-select"><span>Status</span><select className="control" value={statusFilter} onChange={e=>{setStatusFilter(e.target.value as 'all'|'active'|'draft');setPage(1)}}><option value="all">All statuses</option><option value="active">Active</option><option value="draft">Draft</option></select></label></div></div>
  <div className="table-wrap"><table><thead><tr><th>Title</th><th>SKU</th><th>Active</th><th>Price</th><th className="actions-cell"><span className="actions-heading">Actions <button className="table-refresh-icon" data-tooltip="Refresh" aria-label="Refresh table" onClick={()=>void load()}><RefreshCw size={15}/></button></span></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.sku}</td><td><button className={'status-toggle '+(r.status==='Active'?'on':'')} aria-label={r.status==='Active'?'Deactivate product':'Activate product'} disabled={!canEdit} onClick={async()=>{if(!canEdit)return;setError('');const{error}=await supabase!.from('products').update({status:r.status==='Active'?'Draft':'Active'}).eq('id',r.id);if(error){setError(error.message);return}void load()}}><span/></button></td><td>{String.fromCharCode(36)+Number(r.price).toFixed(2)}</td><td className="actions-cell"><div className="table-actions"><button className="icon-button" data-tooltip="View" aria-label={'View '+r.title} onClick={async()=>{const{data:fresh}=await supabase!.from('products').select('*').eq('id',r.id).single();setDetails({product:fresh||r,mode:'view'})}}><Eye size={18}/></button>{canEdit&&<><button className="icon-button" data-tooltip="Edit" aria-label={'Edit '+r.title} onClick={async()=>{const{data:fresh}=await supabase!.from('products').select('*').eq('id',r.id).single();setDetails({product:fresh||r,mode:'edit'})}}><Pencil size={18}/></button><button className="icon-button error" data-tooltip="Delete" aria-label={'Delete '+r.title} onClick={()=>{setError('');setDeleting(r)}}><Trash2 size={18}/></button></>}</div></td></tr>)}</tbody><tfoot><tr><td colSpan={5}><div className="category-pagination"><div className="table-size"><span>Rows per page</span><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option><option>100</option></select></div><span className="pagination-range">{count?Math.min((page-1)*pageSize+1,count):0}–{Math.min(page*pageSize,count)} of {count}</span><div className="pagination-controls"><button className="pagination-button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>Page {page} of {Math.max(1,Math.ceil(count/pageSize))}</span><button className="pagination-button" disabled={page>=Math.ceil(count/pageSize)} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></div></td></tr></tfoot></table></div>
  {adding&&<Modal title="Add product" onClose={()=>setAdding(false)}><form className="editor-form product-modern-form" onSubmit={guardSubmit(saveNew)}>
   <div className="product-form-section"><div className="product-form-section-head"><span>01</span><div><h3>Product details</h3><p>Core information customers and staff will use.</p></div></div><div className="product-form-grid"><label>Title<input name="title" required autoFocus placeholder="Product title"/></label><label>SKU<input name="sku" required placeholder="e.g. YAQ-001"/></label><label className="full">Description<textarea name="description" placeholder="Describe the product…"/></label><label>Price (USD)<input name="price" type="number" min="0" step=".01" required placeholder="0.00"/></label><label>Category<select name="category_id"><option value="">No category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Master design<select name="design_id"><option value="">No master design</option>{designs.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label></div></div>
   <div className="product-form-section"><div className="product-form-section-head"><span>02</span><div><h3>Simple product inventory</h3><p>Optional stock source for products that do not use variants.</p></div></div><div className="product-form-grid"><label>Inventory item<select name="inventory_item_id"><option value="">Use variants instead</option>{inventory.map(i=><option key={i.id} value={i.id}>{i.title} · {i.quantity} physical</option>)}</select></label><label>Stock allocation<input name="stock_allocation" type="number" min="0" defaultValue="0"/><small>Only used when this product has no variants.</small></label></div></div>
   <div className="product-form-section"><div className="product-form-section-head"><span>03</span><div><h3>Store visibility</h3><p>Control where and how this product is highlighted.</p></div></div><div className="product-toggle-grid"><label><div><strong>Active on website</strong><small>Publish this product in the store.</small></div><span className="form-toggle"><input name="status" type="checkbox"/><span className="toggle-track"><span/></span></span></label><label><div><strong>Featured</strong><small>Highlight in featured placements.</small></div><span className="form-toggle"><input name="featured" type="checkbox"/><span className="toggle-track"><span/></span></span></label><label><div><strong>Bestseller</strong><small>Mark as a popular product.</small></div><span className="form-toggle"><input name="bestseller" type="checkbox"/><span className="toggle-track"><span/></span></span></label><label><div><strong>New arrival</strong><small>Show the new-arrival treatment.</small></div><span className="form-toggle"><input name="new_arrival" type="checkbox"/><span className="toggle-track"><span/></span></span></label></div></div>
   <div className="product-form-section"><div className="product-form-section-head"><span>04</span><div><h3>Search & SEO</h3><p>Optional metadata for search engines and sharing.</p></div></div><div className="product-form-grid"><label>SEO title<input name="seo_title" placeholder="Optional SEO title"/></label><label>SEO description<textarea name="seo_description" placeholder="Optional search description"/></label></div></div>
   <div className="product-form-actions"><button type="button" className="secondary-button" onClick={()=>setAdding(false)}>Cancel</button><button className="primary-button">Create product</button></div>
  </form></Modal>}
  {details&&<ProductDetails product={details.product} mode={details.mode} permissions={permissions} onClose={()=>setDetails(null)} onSaved={()=>void load()}/>}
  {deleting&&<Modal title="Delete product?" onClose={()=>setDeleting(null)}><div className="confirm-body modern-confirm"><div className="danger-icon"><Trash2 size={21}/></div><div><h3>Remove “{deleting.title}”?</h3><p>This product can only be deleted when it has no order or inventory history.</p></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setDeleting(null)}>Cancel</button><button className="danger-button" onClick={remove}>Delete product</button></div></div></Modal>}
 {error&&<ErrorPopup message={error} onClose={()=>setError('')}/>} </section>
}