import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Eye, Pencil, Plus, Trash2, WalletCards } from 'lucide-react';
import { BrandLoader } from '../BrandLoader';
import { supabase } from '../lib/supabase';
import { Modal } from './Modal';
import { guardSubmit } from './submitGuard';

const money=(n:number)=>'$'+Number(n||0).toFixed(2);
export function ResourcesAdmin({permissions}:{permissions:string[]}){
 const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState(''),[viewing,setViewing]=useState<any|null>(null),[edit,setEdit]=useState<any|null|undefined>(undefined),[deleting,setDeleting]=useState<any|null>(null);
 const canEdit=permissions.includes('resources.edit'),grandTotal=useMemo(()=>rows.reduce((sum,r)=>sum+Number(r.quantity)*Number(r.unit_price),0),[rows]);
 async function load(){setLoading(true);const{data,error}=await supabase!.from('business_resources').select('*').order('created_at',{ascending:false});if(error)setError(error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget),name=String(fd.get('name')||'').trim(),notes=String(fd.get('notes')||'').trim(),quantity=Number(fd.get('quantity')),unit_price=Number(fd.get('unit_price'));if(!name||!Number.isFinite(quantity)||quantity<0||!Number.isFinite(unit_price)||unit_price<0){setError('Enter a name, quantity and valid unit price.');return}const q=edit?.id?supabase!.from('business_resources').update({name,quantity,unit_price,notes,updated_at:new Date().toISOString()}).eq('id',edit.id):supabase!.from('business_resources').insert({name,quantity,unit_price,notes});const{error}=await q;if(error){setError(error.message);return}setSuccess(edit?.id?'Resource updated successfully.':'Resource added successfully.')}
 async function remove(){if(!deleting)return;const{error}=await supabase!.from('business_resources').delete().eq('id',deleting.id);if(error){setError(error.message);return}setDeleting(null);void load()}
 return <section className="admin-page resources-page"><div className="page-title"><div><p className="eyebrow">PARTNER COSTS</p><h1>Resources</h1><p className="resources-subtitle">Track shared resources, quantities and what has been invested.</p></div>{canEdit&&<button className="primary-button add-record-button" onClick={()=>setEdit(null)}><Plus size={16}/> Add resource</button>}</div>
 <div className="resources-summary"><div className="resource-summary-card peach"><span>Total invested</span><strong>{money(grandTotal)}</strong><small>Across {rows.length} resource{rows.length===1?'':'s'}</small></div><div className="resource-summary-card lavender"><WalletCards size={22}/><span>Shared cost ledger</span><small>Unit price × quantity is calculated automatically.</small></div></div>
 {error&&<div className="form-error">{error}</div>}<div className="table-wrap resources-table"><table><thead><tr><th>Resource</th><th>Quantity</th><th>Unit price</th><th>Total</th><th className="actions-cell">Actions</th></tr></thead><tbody>{loading&&<tr><td colSpan={5}><div className="table-empty-state"><BrandLoader label="Loading resources" compact/></div></td></tr>}{!loading&&!rows.length&&<tr><td colSpan={5}><div className="table-empty-state"><strong>No resources yet</strong><span>Add your first shared cost or purchased resource.</span></div></td></tr>}{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong>{r.notes&&<small className="resource-note">{r.notes}</small>}</td><td>{Number(r.quantity).toLocaleString()} pcs</td><td>{money(r.unit_price)}</td><td><span className="resource-total-pill">{money(Number(r.quantity)*Number(r.unit_price))}</span></td><td className="actions-cell"><div className="table-actions"><button className="icon-button" data-tooltip="View" onClick={()=>setViewing(r)}><Eye size={18}/></button>{canEdit&&<><button className="icon-button" data-tooltip="Edit" onClick={()=>setEdit(r)}><Pencil size={18}/></button><button className="icon-button error" data-tooltip="Delete" onClick={()=>setDeleting(r)}><Trash2 size={18}/></button></>}</div></td></tr>)}</tbody></table></div>
 {viewing&&<Modal title="Resource details" onClose={()=>setViewing(null)}><div className="resource-view"><span className="section-kicker">RESOURCE</span><h3>{viewing.name}</h3><div className="resource-view-grid"><div><span>Quantity</span><strong>{viewing.quantity} pcs</strong></div><div><span>Unit price</span><strong>{money(viewing.unit_price)}</strong></div><div className="resource-view-total"><span>Total value</span><strong>{money(Number(viewing.quantity)*Number(viewing.unit_price))}</strong></div><div><span>Notes</span><strong>{viewing.notes||'—'}</strong></div></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setViewing(null)}>Close</button>{canEdit&&<button className="primary-button" onClick={()=>{const r=viewing;setViewing(null);setEdit(r)}}><Pencil size={15}/> Edit</button>}</div></div></Modal>}
 {edit!==undefined&&<Modal title={edit?'Edit resource':'Add resource'} onClose={()=>setEdit(undefined)}><form className="editor-form resource-editor" onSubmit={guardSubmit(save)}><label className="full">Resource name<input name="name" required autoFocus defaultValue={edit?.name||''} placeholder="e.g. Acrylic L shape"/></label><label>Quantity<input name="quantity" type="number" min="0" step="0.01" required defaultValue={edit?.quantity??1}/></label><label>Unit price (USD)<input name="unit_price" type="number" min="0" step="0.01" required defaultValue={edit?.unit_price??0}/></label><label className="full">Notes<textarea name="notes" rows={3} defaultValue={edit?.notes||''} placeholder="Optional details…"/></label><div className="modal-actions full"><button type="button" className="secondary-button" onClick={()=>setEdit(undefined)}>Cancel</button><button className="primary-button">{edit?'Save changes':'Add resource'}</button></div></form></Modal>}
 {success&&<Modal title="Saved successfully" compact onClose={()=>{setSuccess('');setEdit(undefined);void load()}}><div className="modern-confirm design-success-confirm"><span className="design-success-icon"><CheckCircle2 size={21}/></span><div><h3>{success}</h3><p>The shared resource total has been updated.</p></div><div className="modal-actions"><button className="primary-button" onClick={()=>{setSuccess('');setEdit(undefined);void load()}}>OK</button></div></div></Modal>}
 {deleting&&<Modal title="Delete resource?" onClose={()=>setDeleting(null)}><div className="confirm-body modern-confirm"><div className="danger-icon"><Trash2 size={21}/></div><div><h3>Remove “{deleting.name}”?</h3><p>This permanently removes it from the shared resources ledger.</p></div><div className="modal-actions"><button className="secondary-button" onClick={()=>setDeleting(null)}>Cancel</button><button className="danger-button" onClick={remove}>Delete</button></div></div></Modal>}
 </section>
}