import {guardSubmit} from './submitGuard';
import { FormEvent, useEffect, useState } from 'react';
import { Globe2, Image as ImageIcon, Mail, MessageCircle, Phone, Save, Settings as SettingsIcon, Trash2, Truck, Upload, WalletCards } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { ErrorPopup } from './ErrorPopup';

export function SettingsAdmin({permissions}:{permissions:string[]}){
 const canEdit=permissions.includes('settings.edit');
 const [deliveryFee,setDeliveryFee]=useState('0.00'),[logoUrl,setLogoUrl]=useState(''),[logoUploading,setLogoUploading]=useState(false),[siteName,setSiteName]=useState('YAQEEN'),[tagline,setTagline]=useState('A MORE MEANINGFUL LIFE'),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[phoneIsWhatsapp,setPhoneIsWhatsapp]=useState(false),[shippingPayment,setShippingPayment]=useState(''),[codEnabled,setCodEnabled]=useState(true),[whishEnabled,setWhishEnabled]=useState(false),[confirmationTitle,setConfirmationTitle]=useState('Thank you. Your reminder is on its way.'),[confirmationMessage,setConfirmationMessage]=useState('We’ve received your order and will prepare it for delivery.'),[confirmationButton,setConfirmationButton]=useState('Continue shopping'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{(async()=>{setLoading(true);const{data,error}=await supabase!.from('site_settings').select('key,value').in('key',['commerce','website']);if(error)setError(error.message);else{const commerce=data?.find(x=>x.key==='commerce')?.value||{},website=data?.find(x=>x.key==='website')?.value||{};setDeliveryFee(Number(commerce.delivery_fee||0).toFixed(2));setCodEnabled(commerce.cod_enabled!==false);setWhishEnabled(Boolean(commerce.whish_enabled));setLogoUrl(website.logo_url||'');setSiteName(website.site_name||'YAQEEN');setTagline(website.site_tagline||'A MORE MEANINGFUL LIFE');setEmail(website.email||'');setPhone(website.phone||'');setPhoneIsWhatsapp(Boolean(website.phone)&&website.whatsapp===website.phone);setShippingPayment(website.shipping_payment||'');setConfirmationTitle(website.confirmation_title||'Thank you. Your reminder is on its way.');setConfirmationMessage(website.confirmation_message||'We’ve received your order and will prepare it for delivery.');setConfirmationButton(website.confirmation_button||'Continue shopping')}setLoading(false)})()},[]);
 async function uploadLogo(file:File){if(!canEdit||!supabase)return;setLogoUploading(true);setError('');const ext=(file.name.split('.').pop()||'png').toLowerCase();const path='logo-'+Date.now()+'.'+ext;const{error:uploadError}=await supabase.storage.from('website-assets').upload(path,file,{upsert:true,contentType:file.type||undefined});if(uploadError){setLogoUploading(false);return setError(uploadError.message)}const{data}=supabase.storage.from('website-assets').getPublicUrl(path);setLogoUrl(data.publicUrl);setLogoUploading(false)}
 async function deleteLogo(){if(!canEdit||!logoUrl)return;setLogoUrl('')}
 async function save(e:FormEvent){e.preventDefault();setSaved(false);const usd=Number(deliveryFee);if(!Number.isFinite(usd)||usd<0||usd>1000)return setError('Delivery fee must be a valid USD amount between $0.00 and $1,000.00.');if(!siteName.trim())return setError('Website name is required.');if(email&& !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return setError('Enter a valid website email address.');setSaving(true);const fee=Number(usd.toFixed(2));const results=await Promise.all([supabase!.from('site_settings').update({value:{currency:'USD',delivery_fee:fee,cod_enabled:codEnabled,whish_enabled:whishEnabled}}).eq('key','commerce'),supabase!.from('site_settings').update({value:{site_name:siteName.trim(),logo_url:logoUrl,site_tagline:tagline.trim(),email:email.trim(),phone:phone.trim(),whatsapp:phoneIsWhatsapp?phone.trim():'',shipping_payment:shippingPayment.trim(),confirmation_title:confirmationTitle.trim(),confirmation_message:confirmationMessage.trim(),confirmation_button:confirmationButton.trim()}}).eq('key','website')]);setSaving(false);const failure=results.find(r=>r.error)?.error;if(failure)return setError(failure.message);setDeliveryFee(usd.toFixed(2));setSaved(true);setTimeout(()=>setSaved(false),2500)}
 return <section className="admin-page settings-page"><div className="page-title"><div><p className="eyebrow">GLOBAL CONFIGURATION</p><h1>Settings</h1></div></div>{loading?<div className="settings-loading">Loading settings…</div>:<form onSubmit={guardSubmit(save)} className="settings-stack">
  <div className="settings-card"><div className="settings-card-head"><span className="settings-card-icon"><Globe2 size={20}/></span><div><h2>Website identity & contact</h2><p>Global information used across the public website.</p></div></div><div className="settings-fields settings-global-fields">
   <div className="settings-logo-field full"><div><span className="settings-field-label"><ImageIcon size={16}/> Main logo</span><small>Used as the primary logo in the website header and footer. PNG, JPG, WebP or SVG.</small></div><div className="settings-logo-control">{logoUrl?<div className="settings-logo-preview"><img src={logoUrl} alt="Website logo preview"/></div>:<div className="settings-logo-empty"><ImageIcon size={24}/><span>No logo uploaded</span></div>}<div className="settings-logo-actions"><label className={'secondary-button '+(!canEdit||logoUploading?'disabled':'')}><Upload size={15}/>{logoUploading?'Uploading…':logoUrl?'Replace logo':'Upload logo'}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" disabled={!canEdit||logoUploading} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadLogo(file);e.currentTarget.value=''}}/></label>{logoUrl&&<button type="button" className="secondary-button settings-logo-delete" disabled={!canEdit||logoUploading} onClick={deleteLogo}><Trash2 size={15}/> Delete</button>}</div></div></div><label><span className="settings-field-label"><Globe2 size={16}/> Website name</span><input value={siteName} disabled={!canEdit} onChange={e=>setSiteName(e.target.value)}/><small>Main public brand name.</small></label>
   <label><span className="settings-field-label"><Globe2 size={16}/> Website tagline</span><input value={tagline} disabled={!canEdit} onChange={e=>setTagline(e.target.value)}/><small>Global brand tagline.</small></label>
   <label><span className="settings-field-label"><Mail size={16}/> Email</span><input type="email" value={email} disabled={!canEdit} onChange={e=>setEmail(e.target.value)} placeholder="hello@example.com"/><small>Public contact email.</small></label>
   <label><span className="settings-field-label"><Phone size={16}/> Phone number</span><input value={phone} disabled={!canEdit} onChange={e=>setPhone(e.target.value)} placeholder="+961 ..."/><small>Public phone number.</small></label>
   <label className="settings-whatsapp-toggle"><span className="settings-field-label"><MessageCircle size={16}/> WhatsApp</span><button type="button" className={'crm-toggle '+(phoneIsWhatsapp?'is-on':'')} role="switch" aria-checked={phoneIsWhatsapp} disabled={!canEdit||!phone.trim()} onClick={()=>setPhoneIsWhatsapp(v=>!v)}><span/></button><small>Use the phone number above for WhatsApp.</small></label><label className="full"><span className="settings-field-label"><Truck size={16}/> Shipping & payment</span><textarea value={shippingPayment} disabled={!canEdit} onChange={e=>setShippingPayment(e.target.value)} placeholder="Shipping and payment information shown on every product page."/><small>Global text shown in the Shipping & payment section on all product pages.</small></label>
  </div></div>
  <div className="settings-card"><div className="settings-card-head"><span className="settings-card-icon"><Globe2 size={20}/></span><div><h2>Order confirmation</h2><p>Manage the message customers see after successfully placing an order.</p></div></div><div className="settings-fields settings-global-fields"><label className="full"><span className="settings-field-label">Confirmation title</span><input value={confirmationTitle} disabled={!canEdit} maxLength={120} onChange={e=>setConfirmationTitle(e.target.value)}/><small>Main success heading shown after checkout.</small></label><label className="full"><span className="settings-field-label">Confirmation message</span><textarea value={confirmationMessage} disabled={!canEdit} maxLength={500} onChange={e=>setConfirmationMessage(e.target.value)}/><small>Short message displayed below the order details.</small></label><label><span className="settings-field-label">Button label</span><input value={confirmationButton} disabled={!canEdit} maxLength={40} onChange={e=>setConfirmationButton(e.target.value)}/><small>Label for the button returning customers to the shop.</small></label></div></div>
  <div className="settings-card"><div className="settings-card-head"><span className="settings-card-icon"><SettingsIcon size={20}/></span><div><h2>Commerce</h2><p>Configure the defaults used for storefront orders.</p></div></div><div className="settings-fields"><label><span className="settings-field-label"><WalletCards size={16}/> Currency</span><input value="USD" disabled readOnly/><small>Prices are entered and displayed in USD throughout the CRM.</small></label><label><span className="settings-field-label"><Truck size={16}/> Delivery fee</span><div className="settings-money-input"><span>$</span><input type="number" min="0" max="1000" step=".01" value={deliveryFee} disabled={!canEdit} onChange={e=>setDeliveryFee(e.target.value)}/></div><small>Flat delivery fee per order in USD.</small></label><label><span className="settings-field-label"><WalletCards size={16}/> Cash on Delivery (COD)</span><button type="button" className={'crm-toggle '+(codEnabled?'is-on':'')} role="switch" aria-checked={codEnabled} disabled={!canEdit} onClick={()=>setCodEnabled(v=>!v)}><span/></button><small>Allow customers to pay when the order is delivered.</small></label><label><span className="settings-field-label"><WalletCards size={16}/> Whish Money</span><button type="button" className={'crm-toggle '+(whishEnabled?'is-on':'')} role="switch" aria-checked={whishEnabled} disabled={!canEdit} onClick={()=>setWhishEnabled(v=>!v)}><span/></button><small>Allow customers to choose Whish Money at checkout.</small></label></div></div>
  {canEdit?<div className="settings-actions settings-page-actions">{saved&&<span className="settings-saved">Settings saved</span>}<button className="primary-button" disabled={saving}><Save size={16}/>{saving?'Saving…':'Save settings'}</button></div>:<p className="muted small settings-readonly">You have view-only access to these settings.</p>}
 </form>}{error&&<ErrorPopup message={error} onClose={()=>setError('')}/>}</section>
}