import { BrandLoader } from '../BrandLoader';
import {guardSubmit} from './submitGuard';
import { FormEvent, useEffect, useState } from 'react';
import { Globe2, Image as ImageIcon, Mail, MessageCircle, Phone, Save, Settings as SettingsIcon, Trash2, Truck, Upload, WalletCards } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { uploadResponsiveImage } from '../lib/images';
import { ErrorPopup } from './ErrorPopup';

function mediaDisplayName(item:any){
 const label=item.user_metadata?.label||item.metadata?.label||item.metadata?.user_metadata?.label;
 if(typeof label==='string'&&label.trim())return label.trim();
 return item.name.replace(/^media-\d+-/,'').replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ').trim()||item.name;
}

export function SettingsAdmin({permissions}:{permissions:string[]}){
 const canEdit=permissions.includes('settings.edit');
 const [activeTab,setActiveTab]=useState<'website'|'media'|'commerce'>('website');
 const [media,setMedia]=useState<any[]>([]),[mediaBusy,setMediaBusy]=useState(false),[mediaAddOpen,setMediaAddOpen]=useState(false),[mediaLabel,setMediaLabel]=useState(''),[mediaFile,setMediaFile]=useState<File|null>(null),[deliveryFee,setDeliveryFee]=useState('0.00'),[siteName,setSiteName]=useState('YAQEEN'),[gaMeasurementId,setGaMeasurementId]=useState(''),[faviconUrl,setFaviconUrl]=useState(''),[tagline,setTagline]=useState('A MORE MEANINGFUL LIFE'),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[phoneIsWhatsapp,setPhoneIsWhatsapp]=useState(false),[shippingPayment,setShippingPayment]=useState(''),[codEnabled,setCodEnabled]=useState(true),[whishEnabled,setWhishEnabled]=useState(false),[pickupEnabled,setPickupEnabled]=useState(false),[whishMessage,setWhishMessage]=useState('Pay your order through Whish Money.'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 async function loadMedia(){if(!supabase)return;const storage=supabase.storage.from('website-media');const{data,error}=await storage.list('',{limit:100,sortBy:{column:'created_at',order:'desc'}});if(error)return setError(error.message);setMedia((data||[]).filter(x=>x.name&&!x.name.startsWith('.')).map(x=>({...x,url:storage.getPublicUrl(x.name).data.publicUrl})))}
 useEffect(()=>{void loadMedia();(async()=>{setLoading(true);const{data,error}=await supabase!.from('site_settings').select('key,value').in('key',['commerce','website']);if(error)setError(error.message);else{const commerce=data?.find(x=>x.key==='commerce')?.value||{},website=data?.find(x=>x.key==='website')?.value||{};setDeliveryFee(Number(commerce.delivery_fee||0).toFixed(2));setCodEnabled(commerce.cod_enabled!==false);setWhishEnabled(Boolean(commerce.whish_enabled));setPickupEnabled(Boolean(commerce.pickup_enabled));setWhishMessage(commerce.whish_message||'Pay your order through Whish Money.');setSiteName(website.site_name||'YAQEEN');setGaMeasurementId(website.ga_measurement_id||website.google_analytics_id||'');setFaviconUrl(website.favicon_url||'');setTagline(website.site_tagline||'A MORE MEANINGFUL LIFE');setEmail(website.email||'');setPhone(website.phone||'');setPhoneIsWhatsapp(Boolean(website.phone)&&website.whatsapp===website.phone);setShippingPayment(website.shipping_payment||'')}setLoading(false)})()},[]);
 async function addWebsiteMedia(){if(!canEdit||!supabase||!mediaFile)return;if(!/^image\/(jpeg|png|webp|avif|gif|svg\+xml)$/i.test(mediaFile.type))return setError('Use a JPEG, PNG, WebP, AVIF, GIF or SVG image.');if(mediaFile.size>12*1024*1024)return setError('Image must be 12 MB or smaller. For best performance, upload a WebP or AVIF original when possible.');setMediaBusy(true);setError('');const ext=(mediaFile.name.split('.').pop()||'png').toLowerCase();const base=(mediaLabel.trim()||mediaFile.name.replace(/\.[^.]+$/,'')).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')||'image';const path='media-'+Date.now()+'-'+base+'.'+ext;const{error}=await uploadResponsiveImage(supabase.storage,'website-media',path,mediaFile);if(error){setMediaBusy(false);return setError(error.message)}await loadMedia();setMediaLabel('');setMediaFile(null);setMediaAddOpen(false);setMediaBusy(false)}
 async function deleteWebsiteMedia(item:any){if(!canEdit||!supabase)return;setMediaBusy(true);const{error}=await supabase.storage.from('website-media').remove([item.name]);if(error)setError(error.message);else await loadMedia();setMediaBusy(false)}

 async function save(e:FormEvent){e.preventDefault();setSaved(false);const usd=Number(deliveryFee);if(!Number.isFinite(usd)||usd<0||usd>1000)return setError('Delivery fee must be a valid USD amount between $0.00 and $1,000.00.');if(!siteName.trim())return setError('Website name is required.');if(gaMeasurementId.trim()&&!/^G-[A-Z0-9]+$/i.test(gaMeasurementId.trim()))return setError('Google Analytics Measurement ID must look like G-XXXXXXXXXX.');if(email&& !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return setError('Enter a valid website email address.');setSaving(true);const fee=Number(usd.toFixed(2));const results=await Promise.all([supabase!.from('site_settings').update({value:{currency:'USD',delivery_fee:fee,cod_enabled:codEnabled,whish_enabled:whishEnabled,pickup_enabled:pickupEnabled,whish_message:whishMessage.trim()||'Pay your order through Whish Money.'}}).eq('key','commerce'),supabase!.from('site_settings').update({value:{site_name:siteName.trim(),site_tagline:tagline.trim(),ga_measurement_id:gaMeasurementId.trim().toUpperCase(),favicon_url:faviconUrl.trim(),email:email.trim(),phone:phone.trim(),whatsapp:phoneIsWhatsapp?phone.trim():'',shipping_payment:shippingPayment.trim()}}).eq('key','website')]);setSaving(false);const failure=results.find(r=>r.error)?.error;if(failure)return setError(failure.message);setDeliveryFee(usd.toFixed(2));setSaved(true);window.dispatchEvent(new CustomEvent('sitefaviconchange',{detail:faviconUrl.trim()}));setTimeout(()=>setSaved(false),2500)}
 return <section className="admin-page settings-page"><div className="page-title"><div><p className="eyebrow">GLOBAL CONFIGURATION</p><h1>Settings</h1></div></div>{loading?<BrandLoader label="Loading settings"/>:<form onSubmit={guardSubmit(save)} className="settings-stack"><nav className="settings-tabs" role="tablist" aria-label="Settings sections"><button type="button" role="tab" aria-selected={activeTab==='website'} className={activeTab==='website'?'is-active':''} onClick={()=>setActiveTab('website')}><Globe2 size={17}/><span>Website</span></button><button type="button" role="tab" aria-selected={activeTab==='media'} className={activeTab==='media'?'is-active':''} onClick={()=>setActiveTab('media')}><ImageIcon size={17}/><span>Media</span></button><button type="button" role="tab" aria-selected={activeTab==='commerce'} className={activeTab==='commerce'?'is-active':''} onClick={()=>setActiveTab('commerce')}><WalletCards size={17}/><span>Commerce</span></button></nav>
  <div className={"settings-tab-panel "+(activeTab==='website'?'is-active':'')} role="tabpanel"><div className="settings-card"><div className="settings-card-head"><span className="settings-card-icon"><Globe2 size={20}/></span><div><h2>Website identity & contact</h2><p>Global information used across the public website.</p></div></div><div className="settings-fields settings-global-fields">
   <label><span className="settings-field-label"><Globe2 size={16}/> Website name</span><input value={siteName} disabled={!canEdit} onChange={e=>setSiteName(e.target.value)}/><small>Main public brand name.</small></label>
   <label><span className="settings-field-label"><Globe2 size={16}/> Website tagline</span><input value={tagline} disabled={!canEdit} onChange={e=>setTagline(e.target.value)}/><small>Global brand tagline.</small></label>
   <label className="full"><span className="settings-field-label"><ImageIcon size={16}/> Favicon</span><input type="url" value={faviconUrl} disabled={!canEdit} onChange={e=>setFaviconUrl(e.target.value)} placeholder="https://…/favicon.png"/><small>Browser tab icon. Upload a square PNG, SVG, ICO or WebP image in Website media, then select it below or paste its public URL.</small>{faviconUrl&&<img src={faviconUrl} alt="Favicon preview" style={{width:48,height:48,objectFit:'contain',marginTop:8}}/>}{media.length>0&&<select aria-label="Choose uploaded favicon" value={media.some(item=>item.url===faviconUrl)?faviconUrl:''} disabled={!canEdit} onChange={e=>setFaviconUrl(e.target.value)}><option value="">Choose from Website media…</option>{media.filter(item=>/\.(png|svg|ico|webp|jpg|jpeg)(\?|$)/i.test(item.url)).map(item=><option key={item.name} value={item.url}>{mediaDisplayName(item)}</option>)}</select>}</label>
   <label className="full"><span className="settings-field-label"><Globe2 size={16}/> Google Analytics 4</span><input value={gaMeasurementId} disabled={!canEdit} onChange={e=>setGaMeasurementId(e.target.value)} placeholder="G-XXXXXXXXXX"/><small>Optional GA4 Measurement ID. Analytics loads only after the visitor accepts optional cookies.</small></label>
   <label><span className="settings-field-label"><Mail size={16}/> Email</span><input type="email" value={email} disabled={!canEdit} onChange={e=>setEmail(e.target.value)} placeholder="hello@example.com"/><small>Public contact email.</small></label>
   <label><span className="settings-field-label"><Phone size={16}/> Phone number</span><input value={phone} disabled={!canEdit} onChange={e=>setPhone(e.target.value)} placeholder="+961 ..."/><small>Public phone number.</small></label>
   <label className="settings-whatsapp-toggle"><span className="settings-field-label"><MessageCircle size={16}/> WhatsApp</span><button type="button" className={'crm-toggle '+(phoneIsWhatsapp?'is-on':'')} role="switch" aria-checked={phoneIsWhatsapp} disabled={!canEdit||!phone.trim()} onClick={()=>setPhoneIsWhatsapp(v=>!v)}><span/></button><small>Use the phone number above for WhatsApp.</small></label><label className="full"><span className="settings-field-label"><Truck size={16}/> Shipping & payment</span><textarea value={shippingPayment} disabled={!canEdit} onChange={e=>setShippingPayment(e.target.value)} placeholder="Shipping and payment information shown on every product page."/><small>Global text shown in the Shipping & payment section on all product pages.</small></label>
  </div></div></div>
  <div className={"settings-tab-panel "+(activeTab==='media'?'is-active':'')} role="tabpanel"><div className="settings-card website-media-card"><div className="settings-card-head"><span className="settings-card-icon"><ImageIcon size={20}/></span><div><h2>Website media</h2><p>Upload reusable images and copy their public URL for use anywhere on the website.</p></div><button type="button" className="secondary-button website-media-upload" disabled={!canEdit||mediaBusy} onClick={()=>setMediaAddOpen(v=>!v)}>+ Add</button></div>{mediaAddOpen&&<div className="website-media-modal" role="dialog" aria-modal="true" aria-label="Add website media" onMouseDown={e=>{if(e.target===e.currentTarget)setMediaAddOpen(false)}}><div className="website-media-modal-card"><div className="website-media-modal-head"><div><h3>Add website media</h3><p>Add a name and choose an image.</p></div><button type="button" className="modal-close" aria-label="Close" onClick={()=>setMediaAddOpen(false)}>×</button></div><div className="website-media-add"><label><span className="settings-field-label">Text / name</span><input value={mediaLabel} onChange={e=>setMediaLabel(e.target.value)} placeholder="e.g. Homepage hero"/></label><label><span className="settings-field-label">Image</span><input type="file" accept="image/jpeg,image/png,image/webp,image/avif,image/gif,image/svg+xml" onChange={e=>setMediaFile(e.target.files?.[0]||null)}/></label><button type="button" className="primary-button" disabled={!mediaFile||mediaBusy} onClick={()=>void addWebsiteMedia()}><Upload size={15}/>{mediaBusy?'Uploading…':'Add media'}</button></div></div></div>}{media.length?<div className="website-media-grid">{media.map(item=><article className="website-media-item" key={item.name}><div className="website-media-thumb"><img src={item.url} alt={mediaDisplayName(item)}/></div><div className="website-media-info"><strong title={mediaDisplayName(item)}>{mediaDisplayName(item)}</strong><div className="website-media-url"><div className="website-media-url-scroll" title={item.url}>{item.url}</div>{canEdit&&<button type="button" className="secondary-button settings-logo-delete" disabled={mediaBusy} onClick={()=>void deleteWebsiteMedia(item)} aria-label={'Delete '+mediaDisplayName(item)}><Trash2 size={15}/></button>}</div></div></article>)}</div>:<div className="website-media-empty"><ImageIcon size={28}/><strong>No website media yet</strong><span>Upload an image to get a reusable public URL.</span></div>}</div></div>
  <div className={"settings-tab-panel "+(activeTab==='commerce'?'is-active':'')} role="tabpanel"><div className="settings-card"><div className="settings-card-head"><span className="settings-card-icon"><SettingsIcon size={20}/></span><div><h2>Commerce</h2><p>Configure the defaults used for storefront orders.</p></div></div><div className="settings-fields"><label><span className="settings-field-label"><WalletCards size={16}/> Currency</span><input value="USD" disabled readOnly/><small>Prices are entered and displayed in USD throughout the CRM.</small></label><label><span className="settings-field-label"><Truck size={16}/> Delivery fee</span><div className="settings-money-input"><span>$</span><input type="number" min="0" max="1000" step=".01" value={deliveryFee} disabled={!canEdit} onChange={e=>setDeliveryFee(e.target.value)}/></div><small>Flat delivery fee per order in USD.</small></label><label><span className="settings-field-label"><WalletCards size={16}/> Cash on Delivery (COD)</span><button type="button" className={'crm-toggle '+(codEnabled?'is-on':'')} role="switch" aria-checked={codEnabled} disabled={!canEdit} onClick={()=>setCodEnabled(v=>!v)}><span/></button><small>Allow customers to pay when the order is delivered.</small></label><label><span className="settings-field-label"><WalletCards size={16}/> Whish Money</span><button type="button" className={'crm-toggle '+(whishEnabled?'is-on':'')} role="switch" aria-checked={whishEnabled} disabled={!canEdit} onClick={()=>setWhishEnabled(v=>!v)}><span/></button><small>Allow customers to choose Whish Money at checkout.</small></label><label><span className="settings-field-label">Whish Money message</span><input value={whishMessage} maxLength={160} disabled={!canEdit} onChange={e=>setWhishMessage(e.target.value)}/><small>Shown beneath Whish Money in both the payment option and order summary.</small></label><label><span className="settings-field-label"><Truck size={16}/> Pick up</span><button type="button" className={'crm-toggle '+(pickupEnabled?'is-on':'')} role="switch" aria-checked={pickupEnabled} disabled={!canEdit} onClick={()=>setPickupEnabled(v=>!v)}><span/></button><small>Show the pick-up option at checkout. Pick-up orders have no delivery fee and do not require an address.</small></label></div></div></div>
  {canEdit?<div className="settings-actions settings-page-actions">{saved&&<span className="settings-saved">Settings saved</span>}<button className="primary-button" disabled={saving}><Save size={16}/>{saving?'Saving…':'Save settings'}</button></div>:<p className="muted small settings-readonly">You have view-only access to these settings.</p>}
 </form>}{error&&<ErrorPopup message={error} onClose={()=>setError('')}/>}</section>
}
