import { FormEvent, useEffect, useState } from 'react';
import { Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { BarChart3, ClipboardList, Globe, Layers, LayoutDashboard, Menu, Package, Settings, Shield, ShoppingBag, Truck, Users, Wallet } from 'lucide-react';
import type { User } from '@supabase/supabase-js';
import { configured, supabase } from './lib/supabase';
import { Categories } from './admin/Categories';
import { ProductsAdmin } from './admin/Products';
import { InventoryAdmin } from './admin/Inventory';

type P={id:string;title:string;slug:string;price:number|null};
type Staff={user:User;profile:{full_name?:string|null};permissions:string[]};

function Products(){const[x,setX]=useState<P[]>([]);useEffect(()=>{supabase?.from('products').select('id,title,slug,price').eq('status','Active').limit(12).then(({data})=>setX((data||[])as P[]))},[]);if(!configured)return <section className="section"><h2>Store setup is in progress</h2></section>;return <section className="section"><small>SHOP</small><h2>Meaningful pieces</h2><div className="grid">{x.map(item=><article key={item.id}><div className="image"/><h3>{item.title}</h3>{item.price!=null&&<p>{'$'+(item.price/100).toFixed(2)}</p>}</article>)}</div></section>}
function Header(){const[o,setO]=useState(false);return <><header className="store-header"><Link className="brand" to="/">YAQEEN <span>يقين</span></Link><nav><Link to="/">Home</Link><Link to="/shop">Shop</Link><Link to="/about">About</Link></nav><button onClick={()=>setO(!o)} aria-label="Menu"><Menu/></button></header>{o&&<aside className="store-drawer"><button onClick={()=>setO(false)}>×</button><Link to="/">Home</Link><Link to="/shop">Shop</Link><Link to="/about">About</Link><Link to="/login">Staff sign in</Link></aside>}</>}
function Page({title}:{title:string}){return <section className="section"><h1>{title}</h1><p>This section is being migrated from the original YAQEEN application.</p></section>}
function Home(){return <><section className="hero"><small>A MORE MEANINGFUL LIFE</small><h1>Little reminders.<br/>Lasting meaning.</h1><p>Thoughtful Islamic acrylic pieces for a more peaceful and purposeful life.</p><Link to="/shop">Shop the collection</Link></section><Products/></>}
function Login(){const nav=useNavigate();const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const{error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setError(error.message);else nav('/admin')}return <main className="login-wrap"><form className="login-card" onSubmit={submit}><Link className="brand" to="/">YAQEEN <span>يقين</span></Link><p className="eyebrow">YAQEEN WORKSPACE</p><h1>Staff sign in</h1><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form></main>}

const links=[['Dashboard','',null,LayoutDashboard],['Categories','categories','products.view',ClipboardList],['Products','products','products.view',Package],['Inventory','inventory','inventory.view',Package],['Orders','orders','orders.view',ShoppingBag],['Production','production','production.view',Layers],['Design Library','designs','designs.view',Layers],['Customers','customers','customers.view',Users],['Messages','inbox','customers.view',Users],['Delivery','deliveries','deliveries.view',Truck],['Payments','payments','payments.view',Wallet],['Website','website','website.view',Globe],['Reports','reports','reports.view',BarChart3],['Users & Roles','users','users.view',Shield],['Audit Log','audit','audit.view',ClipboardList],['Settings','settings','settings.view',Settings]] as const;

function Admin(){const[staff,setStaff]=useState<Staff|null>(null),[loading,setLoading]=useState(true),[denied,setDenied]=useState(false);useEffect(()=>{let live=true;(async()=>{if(!supabase){setDenied(true);setLoading(false);return}const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const[{data:profile},{data:permissions,error}]=await Promise.all([supabase.from('profiles').select('full_name,active').eq('id',user.id).single(),supabase.rpc('my_permissions')]);if(!live)return;if(error||!profile?.active){setDenied(true);setLoading(false);return}setStaff({user,profile,permissions:(permissions||[]) as string[]});setLoading(false)})();return()=>{live=false}},[]);if(loading)return <div className="admin-loading">Loading workspace…</div>;if(!staff&&!denied)return <Navigate to="/login" replace/>;if(denied)return <main className="login-wrap"><div className="login-card"><h1>Access unavailable</h1><p>This account is not an active YAQEEN staff account.</p><button className="primary-button" onClick={()=>supabase?.auth.signOut().then(()=>location.href='/YaqeenShop/login')}>Sign out</button></div></main>;return <div className="admin-shell"><aside className="admin-sidebar"><Link className="brand" to="/">YAQEEN <span>يقين</span></Link><nav>{links.filter(l=>!l[2]||staff!.permissions.includes(l[2])).map(([label,path,,Icon])=><Link key={path} to={'/admin/'+path}><Icon size={17}/><span>{label}</span></Link>)}</nav></aside><div className="admin-main"><header className="admin-top"><div><p className="eyebrow">YAQEEN WORKSPACE</p><span>Thoughtful work. Meaningful things.</span></div><div className="admin-actions"><Link to="/">View store ↗</Link><span>{staff!.profile.full_name||staff!.user.email}</span><button onClick={async()=>{await supabase?.auth.signOut();location.href='/YaqeenShop/login'}}>Sign out</button></div></header><Routes><Route index element={<section className="admin-page"><p className="eyebrow">DASHBOARD</p><h1>Welcome back</h1><p>Your secure YAQEEN workspace is connected.</p></section>}/><Route path="categories" element={<Categories permissions={staff!.permissions}/>}/><Route path="products" element={<ProductsAdmin permissions={staff!.permissions}/>}/><Route path="inventory" element={<InventoryAdmin permissions={staff!.permissions}/>}/><Route path="*" element={<section className="admin-page"><h1>Module migration</h1><p>This CRM section is being migrated.</p></section>}/></Routes></div></div>}

export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/admin/*" element={<Admin/>}/><Route path="*" element={<><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/shop" element={<Products/>}/><Route path="/about" element={<Page title="About YAQEEN"/>}/><Route path="*" element={<Page title="Page not found"/>}/></Routes></main></>}/></Routes>}
